/**
 * Purpose:
 * BP-008 inventory domain engine constants. IP-01 records OPENING_STOCK only.
 *
 * Implementation Package:
 * BP-008 / IP-01 – Inventory Foundation & Stock Item Master
 */

export const INVENTORY_MOVEMENT_TYPES = {
  OPENING_STOCK: "OPENING_STOCK",
  OPENING_BALANCE: "OPENING_BALANCE",
  RECEIPT: "RECEIPT",
  SALE_DEDUCTION: "SALE_DEDUCTION",
  POSITIVE_ADJUSTMENT: "POSITIVE_ADJUSTMENT",
  NEGATIVE_ADJUSTMENT: "NEGATIVE_ADJUSTMENT",
  DAMAGE: "DAMAGE",
  LOSS: "LOSS",
  CUSTOMER_RETURN: "CUSTOMER_RETURN",
  SUPPLIER_RETURN: "SUPPLIER_RETURN",
  TRANSFER_DISPATCH: "TRANSFER_DISPATCH",
  TRANSFER_RECEIPT: "TRANSFER_RECEIPT",
} as const;

export type InventoryMovementType =
  (typeof INVENTORY_MOVEMENT_TYPES)[keyof typeof INVENTORY_MOVEMENT_TYPES];

export const INVENTORY_IP01_MOVEMENT_TYPES = {
  OPENING_STOCK: INVENTORY_MOVEMENT_TYPES.OPENING_STOCK,
} as const;

export const INVENTORY_INBOUND_MOVEMENT_TYPES = {
  OPENING_STOCK: INVENTORY_MOVEMENT_TYPES.OPENING_STOCK,
  OPENING_BALANCE: INVENTORY_MOVEMENT_TYPES.OPENING_BALANCE,
  RECEIPT: INVENTORY_MOVEMENT_TYPES.RECEIPT,
  POSITIVE_ADJUSTMENT: INVENTORY_MOVEMENT_TYPES.POSITIVE_ADJUSTMENT,
  CUSTOMER_RETURN: INVENTORY_MOVEMENT_TYPES.CUSTOMER_RETURN,
  TRANSFER_RECEIPT: INVENTORY_MOVEMENT_TYPES.TRANSFER_RECEIPT,
} as const;

export const INVENTORY_OUTBOUND_MOVEMENT_TYPES = {
  SALE_DEDUCTION: INVENTORY_MOVEMENT_TYPES.SALE_DEDUCTION,
  NEGATIVE_ADJUSTMENT: INVENTORY_MOVEMENT_TYPES.NEGATIVE_ADJUSTMENT,
  DAMAGE: INVENTORY_MOVEMENT_TYPES.DAMAGE,
  LOSS: INVENTORY_MOVEMENT_TYPES.LOSS,
  SUPPLIER_RETURN: INVENTORY_MOVEMENT_TYPES.SUPPLIER_RETURN,
  TRANSFER_DISPATCH: INVENTORY_MOVEMENT_TYPES.TRANSFER_DISPATCH,
} as const;

export const INVENTORY_ADJUSTMENT_MOVEMENT_TYPES = {
  POSITIVE_ADJUSTMENT: INVENTORY_MOVEMENT_TYPES.POSITIVE_ADJUSTMENT,
  NEGATIVE_ADJUSTMENT: INVENTORY_MOVEMENT_TYPES.NEGATIVE_ADJUSTMENT,
  DAMAGE: INVENTORY_MOVEMENT_TYPES.DAMAGE,
  LOSS: INVENTORY_MOVEMENT_TYPES.LOSS,
  CUSTOMER_RETURN: INVENTORY_MOVEMENT_TYPES.CUSTOMER_RETURN,
  SUPPLIER_RETURN: INVENTORY_MOVEMENT_TYPES.SUPPLIER_RETURN,
} as const;

export const INVENTORY_OPENING_MOVEMENT_TYPES = {
  OPENING_STOCK: INVENTORY_MOVEMENT_TYPES.OPENING_STOCK,
  OPENING_BALANCE: INVENTORY_MOVEMENT_TYPES.OPENING_BALANCE,
} as const;
