export const currencies = [
  {
    code: "KES",
    name: "Kenyan Shilling",
    symbol: "KSh",
    decimalPlaces: 2,
    displayOrder: 1,
    isActive: true,
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    symbol: "USh",
    decimalPlaces: 0,
    displayOrder: 2,
    isActive: true,
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "TSh",
    decimalPlaces: 2,
    displayOrder: 3,
    isActive: true,
  },
  {
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    decimalPlaces: 2,
    displayOrder: 10,
    isActive: true,
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    decimalPlaces: 2,
    displayOrder: 11,
    isActive: true,
  },
  {
    code: "GBP",
    name: "British Pound",
    symbol: "£",
    decimalPlaces: 2,
    displayOrder: 12,
    isActive: true,
  },
] as const;
