export const industries = [
    {
      code: "COMMERCE",
      name: "Commerce & Trade",
      description: "Retail, wholesale and general trading businesses.",
      iconCode: "commerce",
      displayOrder: 1,
      isActive: true,
    },
    {
      code: "HOSPITALITY",
      name: "Hospitality & Food Services",
      description: "Hotels, restaurants, cafés and catering.",
      iconCode: "hospitality",
      displayOrder: 2,
      isActive: true,
    },
    {
      code: "HEALTHCARE",
      name: "Healthcare",
      description: "Healthcare providers and wellness organizations.",
      iconCode: "healthcare",
      displayOrder: 3,
      isActive: true,
    },
    {
      code: "EDUCATION",
      name: "Education",
      description: "Schools, colleges, universities and training institutions.",
      iconCode: "education",
      displayOrder: 4,
      isActive: true,
    },
    {
      code: "PROPERTY",
      name: "Property",
      description: "Property owners, agents and facility managers.",
      iconCode: "property",
      displayOrder: 5,
      isActive: true,
    },
    {
      code: "AGRICULTURE",
      name: "Agriculture",
      description: "Farming, livestock and agribusiness.",
      iconCode: "agriculture",
      displayOrder: 6,
      isActive: true,
    },
    {
      code: "TRANSPORT",
      name: "Transport & Logistics",
      description: "Transportation, courier and logistics businesses.",
      iconCode: "transport",
      displayOrder: 7,
      isActive: true,
    },
    {
      code: "MANUFACTURING",
      name: "Manufacturing",
      description: "Industrial production and processing businesses.",
      iconCode: "manufacturing",
      displayOrder: 8,
      isActive: true,
    },
    {
      code: "PROFESSIONAL",
      name: "Professional Services",
      description: "Consulting, legal, accounting and IT services.",
      iconCode: "professional",
      displayOrder: 9,
      isActive: true,
    },
    {
      code: "FINANCIAL",
      name: "Financial Services",
      description: "Financial institutions and financial service providers.",
      iconCode: "financial",
      displayOrder: 10,
      isActive: true,
    },
    {
      code: "NON_PROFIT",
      name: "Non-Profit",
      description: "NGOs, charities, foundations and community organizations.",
      iconCode: "non-profit",
      displayOrder: 11,
      isActive: true,
    },
    {
      code: "GOVERNMENT",
      name: "Government & Public Sector",
      description: "Government ministries, agencies and public institutions.",
      iconCode: "government",
      displayOrder: 12,
      isActive: true,
    },
  ];