/**
 * Purpose:
 * Platform inventory operation control catalogue.
 *
 * Implementation Package:
 * BP-008 / IP-02 – Stock Receiving & Opening Balances
 */

export const inventoryOperationControls = [
  {
    code: "STOCK_RECEIVING",
    name: "Stock receiving",
    description: "Supplier or other external stock receipts posted to the inventory ledger.",
    movementType: "RECEIPT",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 10,
    isActive: true,
  },
  {
    code: "OPENING_BALANCE",
    name: "Opening balance",
    description: "Opening stock balances when a business starts using inventory.",
    movementType: "OPENING_BALANCE",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 20,
    isActive: true,
  },
  {
    code: "STOCK_RESERVATION",
    name: "Stock reservation",
    description: "Hold available stock for a confirmed sale without reducing on-hand.",
    movementType: "RESERVATION",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 30,
    isActive: true,
  },
  {
    code: "STOCK_DEDUCTION",
    name: "Stock deduction",
    description: "Deduct reserved stock when a confirmed sale is fulfilled.",
    movementType: "SALE_DEDUCTION",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 40,
    isActive: true,
  },
  {
    code: "STOCK_RESERVATION_RELEASE",
    name: "Reservation release",
    description: "Release an unfulfilled reservation back to available stock.",
    movementType: "RESERVATION",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 50,
    isActive: true,
  },
  {
    code: "STOCK_ADJUSTMENT",
    name: "Stock adjustment",
    description: "Controlled damage, loss, and quantity corrections posted to the inventory ledger.",
    movementType: "POSITIVE_ADJUSTMENT",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 60,
    isActive: true,
  },
  {
    code: "CUSTOMER_RETURN",
    name: "Customer return",
    description: "Physical customer returns that increase on-hand through a new ledger movement.",
    movementType: "CUSTOMER_RETURN",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 70,
    isActive: true,
  },
  {
    code: "SUPPLIER_RETURN",
    name: "Supplier return",
    description: "Stock returned to a supplier, decreasing on-hand through a new ledger movement.",
    movementType: "SUPPLIER_RETURN",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 80,
    isActive: true,
  },
  {
    code: "STOCKTAKE",
    name: "Stocktake",
    description: "Physical count and ledger reconciliation through controlled stock adjustments.",
    movementType: "POSITIVE_ADJUSTMENT",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 90,
    isActive: true,
  },
  {
    code: "INVENTORY_CONTROL_CONFIG",
    name: "Inventory control settings",
    description: "Save or approve item and location stock-control thresholds.",
    movementType: "CONTROL",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 100,
    isActive: true,
  },
  {
    code: "OPS_INCIDENT_RESOLUTION",
    name: "Exception resolution",
    description: "Resolve or close an inventory exception after investigation.",
    movementType: "CONTROL",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 110,
    isActive: true,
  },
  {
    code: "STOCK_TRANSFER",
    name: "Stock transfer",
    description: "Move available stock between inventory locations.",
    movementType: "TRANSFER_DISPATCH",
    requiresApproval: false,
    overReceiptPolicy: "BLOCK",
    displayOrder: 120,
    isActive: true,
  },
] as const;
