/**
 * Purpose:
 * Example provider/channel capability metadata seed.
 * Values are configuration — BP-007 must not hard-code these limits.
 *
 * Implementation Package:
 * BP-007 / IP-01 – Payment Obligation & Provider Integration Foundation
 */

export const paymentChannelCapabilities = [
  {
    paymentChannelCode: "STK_PUSH",
    minAmount: "1",
    maxAmount: null as string | null,
    dailyLimit: null as string | null,
    transactionLimit: null as string | null,
    supportedCurrencies: ["KES"],
    supportsInitiation: true,
    supportsRefund: true,
    supportsStatusQuery: true,
    isAvailable: true,
  },
  {
    paymentChannelCode: "PAYBILL",
    minAmount: "1",
    maxAmount: null as string | null,
    dailyLimit: null as string | null,
    transactionLimit: null as string | null,
    supportedCurrencies: ["KES"],
    supportsInitiation: true,
    supportsRefund: false,
    supportsStatusQuery: true,
    isAvailable: true,
  },
  {
    paymentChannelCode: "BUY_GOODS",
    minAmount: "1",
    maxAmount: null as string | null,
    dailyLimit: null as string | null,
    transactionLimit: null as string | null,
    supportedCurrencies: ["KES"],
    supportsInitiation: true,
    supportsRefund: false,
    supportsStatusQuery: true,
    isAvailable: true,
  },
  {
    paymentChannelCode: "USSD",
    minAmount: "1",
    maxAmount: null as string | null,
    dailyLimit: null as string | null,
    transactionLimit: null as string | null,
    supportedCurrencies: ["KES"],
    supportsInitiation: true,
    supportsRefund: false,
    supportsStatusQuery: true,
    isAvailable: true,
  },
  {
    paymentChannelCode: "MOBILE_APP",
    minAmount: null as string | null,
    maxAmount: null as string | null,
    dailyLimit: null as string | null,
    transactionLimit: null as string | null,
    supportedCurrencies: ["KES"],
    supportsInitiation: true,
    supportsRefund: false,
    supportsStatusQuery: false,
    isAvailable: true,
  },
  {
    paymentChannelCode: "INTERNET_BANKING",
    minAmount: null as string | null,
    maxAmount: null as string | null,
    dailyLimit: null as string | null,
    transactionLimit: null as string | null,
    supportedCurrencies: ["KES"],
    supportsInitiation: true,
    supportsRefund: false,
    supportsStatusQuery: false,
    isAvailable: true,
  },
  {
    paymentChannelCode: "BRANCH",
    minAmount: null as string | null,
    maxAmount: null as string | null,
    dailyLimit: null as string | null,
    transactionLimit: null as string | null,
    supportedCurrencies: ["KES"],
    supportsInitiation: false,
    supportsRefund: false,
    supportsStatusQuery: false,
    isAvailable: true,
  },
  {
    paymentChannelCode: "POS",
    minAmount: null as string | null,
    maxAmount: null as string | null,
    dailyLimit: null as string | null,
    transactionLimit: null as string | null,
    supportedCurrencies: ["KES"],
    supportsInitiation: true,
    supportsRefund: true,
    supportsStatusQuery: true,
    isAvailable: true,
  },
];
