export const permissionActions = [
    {
      code: "VIEW",
      name: "View",
      description: "View or read records.",
      displayOrder: 1,
      isActive: true,
    },
    {
      code: "CREATE",
      name: "Create",
      description: "Create new records.",
      displayOrder: 2,
      isActive: true,
    },
    {
      code: "UPDATE",
      name: "Update",
      description: "Modify existing records.",
      displayOrder: 3,
      isActive: true,
    },
    {
      code: "DELETE",
      name: "Delete",
      description: "Delete records.",
      displayOrder: 4,
      isActive: true,
    },
    {
      code: "APPROVE",
      name: "Approve",
      description: "Approve workflow actions.",
      displayOrder: 5,
      isActive: true,
    },
    {
      code: "REJECT",
      name: "Reject",
      description: "Reject workflow actions.",
      displayOrder: 6,
      isActive: true,
    },
    {
      code: "ASSIGN",
      name: "Assign",
      description: "Assign records or tasks.",
      displayOrder: 7,
      isActive: true,
    },
    {
      code: "IMPORT",
      name: "Import",
      description: "Import data into the platform.",
      displayOrder: 8,
      isActive: true,
    },
    {
      code: "EXPORT",
      name: "Export",
      description: "Export data from the platform.",
      displayOrder: 9,
      isActive: true,
    },
    {
      code: "EXECUTE",
      name: "Execute",
      description: "Execute business processes or jobs.",
      displayOrder: 10,
      isActive: true,
    },
    {
      code: "CONFIGURE",
      name: "Configure",
      description: "Manage configuration settings.",
      displayOrder: 11,
      isActive: true,
    },
    {
      code: "ACTIVATE",
      name: "Activate",
      description: "Activate or enable records.",
      displayOrder: 12,
      isActive: true,
    },
    {
      code: "DEACTIVATE",
      name: "Deactivate",
      description: "Deactivate or disable records.",
      displayOrder: 13,
      isActive: true,
    },
  ];