/**
 * Purpose:
 * Typed errors for Product Foundation operations.
 *
 * Implementation Package:
 * BP-003 / IP-001 – Product & Service Foundation
 */

export const PRODUCT_ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  SESSION_REQUIRED: "SESSION_REQUIRED",
  BUSINESS_CONTEXT_REQUIRED: "BUSINESS_CONTEXT_REQUIRED",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  DUPLICATE_PRODUCT_CODE: "DUPLICATE_PRODUCT_CODE",
  INVALID_PRODUCT_TYPE: "INVALID_PRODUCT_TYPE",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  ARCHIVED_PRODUCT_IMMUTABLE: "ARCHIVED_PRODUCT_IMMUTABLE",
  REFERENCE_DATA_MISSING: "REFERENCE_DATA_MISSING",
  OWNER_PARTY_NOT_FOUND: "OWNER_PARTY_NOT_FOUND",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  CLASSIFICATION_NOT_FOUND: "CLASSIFICATION_NOT_FOUND",
  DUPLICATE_CLASSIFICATION_CODE: "DUPLICATE_CLASSIFICATION_CODE",
  CIRCULAR_CLASSIFICATION_HIERARCHY: "CIRCULAR_CLASSIFICATION_HIERARCHY",
  CLASSIFICATION_HAS_ACTIVE_CHILDREN: "CLASSIFICATION_HAS_ACTIVE_CHILDREN",
  CLASSIFICATION_HAS_ACTIVE_PRODUCTS: "CLASSIFICATION_HAS_ACTIVE_PRODUCTS",
  INACTIVE_CLASSIFICATION: "INACTIVE_CLASSIFICATION",
  DUPLICATE_CLASSIFICATION_ASSIGNMENT: "DUPLICATE_CLASSIFICATION_ASSIGNMENT",
  ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",
  PRIMARY_CLASSIFICATION_REQUIRED: "PRIMARY_CLASSIFICATION_REQUIRED",
  UNIT_NOT_FOUND: "UNIT_NOT_FOUND",
  UNIT_CATEGORY_NOT_FOUND: "UNIT_CATEGORY_NOT_FOUND",
  DUPLICATE_UNIT_CODE: "DUPLICATE_UNIT_CODE",
  DUPLICATE_UNIT_SYMBOL: "DUPLICATE_UNIT_SYMBOL",
  INVALID_CONVERSION_FACTOR: "INVALID_CONVERSION_FACTOR",
  UNIT_CATEGORY_MISMATCH: "UNIT_CATEGORY_MISMATCH",
  MULTIPLE_BASE_UNITS: "MULTIPLE_BASE_UNITS",
  ARCHIVED_UNIT_IMMUTABLE: "ARCHIVED_UNIT_IMMUTABLE",
  INVALID_UNIT_STATUS_TRANSITION: "INVALID_UNIT_STATUS_TRANSITION",
  ATTRIBUTE_GROUP_NOT_FOUND: "ATTRIBUTE_GROUP_NOT_FOUND",
  ATTRIBUTE_DEFINITION_NOT_FOUND: "ATTRIBUTE_DEFINITION_NOT_FOUND",
  ATTRIBUTE_ASSIGNMENT_NOT_FOUND: "ATTRIBUTE_ASSIGNMENT_NOT_FOUND",
  DUPLICATE_ATTRIBUTE_GROUP_CODE: "DUPLICATE_ATTRIBUTE_GROUP_CODE",
  DUPLICATE_ATTRIBUTE_CODE: "DUPLICATE_ATTRIBUTE_CODE",
  DUPLICATE_ATTRIBUTE_NAME_IN_GROUP: "DUPLICATE_ATTRIBUTE_NAME_IN_GROUP",
  DUPLICATE_ATTRIBUTE_OPTION_CODE: "DUPLICATE_ATTRIBUTE_OPTION_CODE",
  DUPLICATE_ATTRIBUTE_SCOPE: "DUPLICATE_ATTRIBUTE_SCOPE",
  ARCHIVED_ATTRIBUTE_IMMUTABLE: "ARCHIVED_ATTRIBUTE_IMMUTABLE",
  ARCHIVED_ATTRIBUTE_NOT_ASSIGNABLE: "ARCHIVED_ATTRIBUTE_NOT_ASSIGNABLE",
  INVALID_ATTRIBUTE_DATA_TYPE: "INVALID_ATTRIBUTE_DATA_TYPE",
  INVALID_ATTRIBUTE_VALUE: "INVALID_ATTRIBUTE_VALUE",
  OPTIONS_NOT_ALLOWED_FOR_DATA_TYPE: "OPTIONS_NOT_ALLOWED_FOR_DATA_TYPE",
  OPTIONS_REQUIRED_FOR_DATA_TYPE: "OPTIONS_REQUIRED_FOR_DATA_TYPE",
  INVALID_ATTRIBUTE_STATUS_TRANSITION: "INVALID_ATTRIBUTE_STATUS_TRANSITION",
  VARIANT_NOT_FOUND: "VARIANT_NOT_FOUND",
  DUPLICATE_VARIANT_CODE: "DUPLICATE_VARIANT_CODE",
  DUPLICATE_VARIANT_COMBINATION: "DUPLICATE_VARIANT_COMBINATION",
  ARCHIVED_VARIANT_IMMUTABLE: "ARCHIVED_VARIANT_IMMUTABLE",
  INVALID_VARIANT_STATUS_TRANSITION: "INVALID_VARIANT_STATUS_TRANSITION",
  VARIANT_REQUIRES_DISTINGUISHING_ATTRIBUTE: "VARIANT_REQUIRES_DISTINGUISHING_ATTRIBUTE",
  PARENT_PRODUCT_ARCHIVED: "PARENT_PRODUCT_ARCHIVED",
  VARIANT_NOT_TRANSACTABLE: "VARIANT_NOT_TRANSACTABLE",
  BUNDLE_NOT_FOUND: "BUNDLE_NOT_FOUND",
  DUPLICATE_BUNDLE_CODE: "DUPLICATE_BUNDLE_CODE",
  DUPLICATE_BUNDLE_ITEM: "DUPLICATE_BUNDLE_ITEM",
  ARCHIVED_BUNDLE_IMMUTABLE: "ARCHIVED_BUNDLE_IMMUTABLE",
  INVALID_BUNDLE_STATUS_TRANSITION: "INVALID_BUNDLE_STATUS_TRANSITION",
  BUNDLE_REQUIRES_ITEMS: "BUNDLE_REQUIRES_ITEMS",
  INACTIVE_PRODUCT_NOT_BUNDLEABLE: "INACTIVE_PRODUCT_NOT_BUNDLEABLE",
  ARCHIVED_PRODUCT_NOT_BUNDLEABLE: "ARCHIVED_PRODUCT_NOT_BUNDLEABLE",
  INVALID_BUNDLE_ITEM_VARIANT: "INVALID_BUNDLE_ITEM_VARIANT",
  NESTED_BUNDLE_NOT_ALLOWED: "NESTED_BUNDLE_NOT_ALLOWED",
  INVALID_BUNDLE_ITEM_QUANTITY: "INVALID_BUNDLE_ITEM_QUANTITY",
  PRODUCT_NOT_PUBLISHABLE: "PRODUCT_NOT_PUBLISHABLE",
  PUBLICATION_NOT_FOUND: "PUBLICATION_NOT_FOUND",
  INVALID_PUBLICATION_SCHEDULE: "INVALID_PUBLICATION_SCHEDULE",
  DUPLICATE_CATALOGUE_PUBLICATION: "DUPLICATE_CATALOGUE_PUBLICATION",
  CHANNEL_NOT_FOUND: "CHANNEL_NOT_FOUND",
  INVALID_LIFECYCLE_TRANSITION: "INVALID_LIFECYCLE_TRANSITION",
  INVALID_EFFECTIVE_DATES: "INVALID_EFFECTIVE_DATES",
  MAX_ACTIVE_VERSIONS_EXCEEDED: "MAX_ACTIVE_VERSIONS_EXCEEDED",
  SELF_REPLACEMENT_NOT_ALLOWED: "SELF_REPLACEMENT_NOT_ALLOWED",
  LIFECYCLE_NOT_FOUND: "LIFECYCLE_NOT_FOUND",
  DUPLICATE_OFFERING_RELATIONSHIP: "DUPLICATE_OFFERING_RELATIONSHIP",
  SELF_RELATIONSHIP_NOT_ALLOWED: "SELF_RELATIONSHIP_NOT_ALLOWED",
  CIRCULAR_DEPENDENCY: "CIRCULAR_DEPENDENCY",
  OFFERING_RELATIONSHIP_NOT_FOUND: "OFFERING_RELATIONSHIP_NOT_FOUND",
  OFFERING_DOCUMENT_NOT_FOUND: "OFFERING_DOCUMENT_NOT_FOUND",
  PRICING_CATALOGUE_NOT_FOUND: "PRICING_CATALOGUE_NOT_FOUND",
  PRICING_ITEM_NOT_FOUND: "PRICING_ITEM_NOT_FOUND",
  DUPLICATE_PRICING_CATALOGUE_CODE: "DUPLICATE_PRICING_CATALOGUE_CODE",
  DUPLICATE_ACTIVE_PRICING: "DUPLICATE_ACTIVE_PRICING",
  OVERLAPPING_PRICING_PERIOD: "OVERLAPPING_PRICING_PERIOD",
  INVALID_PRICING_METHOD: "INVALID_PRICING_METHOD",
  INVALID_PRICING_STATUS_TRANSITION: "INVALID_PRICING_STATUS_TRANSITION",
  EXPIRED_PRICING_IMMUTABLE: "EXPIRED_PRICING_IMMUTABLE",
  INVALID_PRICE_RANGE: "INVALID_PRICE_RANGE",
  INVALID_EFFECTIVE_PERIOD: "INVALID_EFFECTIVE_PERIOD",
  METRIC_DEFINITION_NOT_FOUND: "METRIC_DEFINITION_NOT_FOUND",
  ANALYTICS_READ_ONLY: "ANALYTICS_READ_ONLY",
  SNAPSHOT_ALREADY_EXISTS: "SNAPSHOT_ALREADY_EXISTS",
  GOVERNANCE_NOT_FOUND: "GOVERNANCE_NOT_FOUND",
  GOVERNANCE_IMMUTABLE: "GOVERNANCE_IMMUTABLE",
  GOVERNANCE_LOCKED: "GOVERNANCE_LOCKED",
  BUSINESS_OWNER_REQUIRED: "BUSINESS_OWNER_REQUIRED",
} as const;

export type ProductErrorCode =
  (typeof PRODUCT_ERROR_CODES)[keyof typeof PRODUCT_ERROR_CODES];

export class ProductError extends Error {
  readonly code: ProductErrorCode;
  readonly statusCode: number;
  readonly field?: string;

  constructor(
    code: ProductErrorCode,
    message: string,
    statusCode: number,
    field?: string
  ) {
    super(message);
    this.name = "ProductError";
    this.code = code;
    this.statusCode = statusCode;
    this.field = field;
  }
}

export {
  DEFAULT_PRODUCT_USER_MESSAGES as PRODUCT_USER_MESSAGES,
  buildProductUserMessages,
  type ProductUserMessages,
} from "@/modules/product/product-user-messages";
