/**
 * Purpose:
 * Configurable event categories, types, and source modules for Product Timeline.
 *
 * Implementation Package:
 * BP-003 / IP-001 – Product & Service Foundation
 */

export const PRODUCT_TIMELINE_EVENT_CATEGORIES = {
  REGISTRATION: "REGISTRATION",
  LIFECYCLE: "LIFECYCLE",
  GOVERNANCE: "GOVERNANCE",
  OPERATIONS: "OPERATIONS",
  DOCUMENTS: "DOCUMENTS",
  RELATIONSHIPS: "RELATIONSHIPS",
} as const;

export type ProductTimelineEventCategory =
  (typeof PRODUCT_TIMELINE_EVENT_CATEGORIES)[keyof typeof PRODUCT_TIMELINE_EVENT_CATEGORIES];

export const PRODUCT_TIMELINE_EVENT_TYPES = {
  /** IP-001 — active */
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_ACTIVATED: "PRODUCT_ACTIVATED",
  PRODUCT_SUSPENDED: "PRODUCT_SUSPENDED",
  PRODUCT_ARCHIVED: "PRODUCT_ARCHIVED",
  /** IP-002 — classification */
  CLASSIFICATION_CREATED: "CLASSIFICATION_CREATED",
  CLASSIFICATION_UPDATED: "CLASSIFICATION_UPDATED",
  CLASSIFICATION_MOVED: "CLASSIFICATION_MOVED",
  PRODUCT_ASSIGNED: "PRODUCT_ASSIGNED",
  PRODUCT_UNASSIGNED: "PRODUCT_UNASSIGNED",
  /** IP-003 — units of measure */
  UNIT_CREATED: "UNIT_CREATED",
  UNIT_UPDATED: "UNIT_UPDATED",
  UNIT_CONVERSION_CHANGED: "UNIT_CONVERSION_CHANGED",
  UNIT_ACTIVATED: "UNIT_ACTIVATED",
  UNIT_SUSPENDED: "UNIT_SUSPENDED",
  UNIT_ARCHIVED: "UNIT_ARCHIVED",
  /** Future IPs — reserved taxonomy (append-only; no schema change required) */
  PRODUCT_PRICE_CHANGED: "PRODUCT_PRICE_CHANGED",
  PRODUCT_OWNER_CHANGED: "PRODUCT_OWNER_CHANGED",
  PRODUCT_STATUS_CHANGED: "PRODUCT_STATUS_CHANGED",
  PRODUCT_ATTRIBUTE_ADDED: "PRODUCT_ATTRIBUTE_ADDED",
  PRODUCT_BUNDLE_ADDED: "PRODUCT_BUNDLE_ADDED",
  PRODUCT_DOCUMENT_UPLOADED: "PRODUCT_DOCUMENT_UPLOADED",
  PRODUCT_PUBLISHED: "PRODUCT_PUBLISHED",
  /** IP-009 — offering documents */
  OFFERING_DOCUMENT_UPLOADED: "OFFERING_DOCUMENT_UPLOADED",
  OFFERING_DOCUMENT_REPLACED: "OFFERING_DOCUMENT_REPLACED",
  OFFERING_DOCUMENT_VERIFIED: "OFFERING_DOCUMENT_VERIFIED",
  OFFERING_DOCUMENT_REMOVED: "OFFERING_DOCUMENT_REMOVED",
  OFFERING_DOCUMENT_DEACTIVATED: "OFFERING_DOCUMENT_DEACTIVATED",
  /** IP-010 — offering relationships */
  OFFERING_RELATIONSHIP_CREATED: "OFFERING_RELATIONSHIP_CREATED",
  OFFERING_RELATIONSHIP_UPDATED: "OFFERING_RELATIONSHIP_UPDATED",
  OFFERING_RELATIONSHIP_REMOVED: "OFFERING_RELATIONSHIP_REMOVED",
} as const;

export type ProductTimelineEventType =
  (typeof PRODUCT_TIMELINE_EVENT_TYPES)[keyof typeof PRODUCT_TIMELINE_EVENT_TYPES];

export const PRODUCT_TIMELINE_SOURCE_MODULES = {
  PRODUCT_MANAGEMENT: "PRODUCT_MANAGEMENT",
} as const;

export type ProductTimelineSourceModule =
  (typeof PRODUCT_TIMELINE_SOURCE_MODULES)[keyof typeof PRODUCT_TIMELINE_SOURCE_MODULES];

export const PRODUCT_TIMELINE_VISIBILITY = {
  STANDARD: "STANDARD",
  INTERNAL: "INTERNAL",
  RESTRICTED: "RESTRICTED",
} as const;

export type ProductTimelineVisibility =
  (typeof PRODUCT_TIMELINE_VISIBILITY)[keyof typeof PRODUCT_TIMELINE_VISIBILITY];

export const PRODUCT_TIMELINE_DEFAULT_PAGE_SIZE = 20;

export const PRODUCT_TIMELINE_CATEGORY_LABELS: Record<
  ProductTimelineEventCategory,
  string
> = {
  REGISTRATION: "Registration",
  LIFECYCLE: "Lifecycle",
  GOVERNANCE: "Governance",
  OPERATIONS: "Operations",
  DOCUMENTS: "Documents",
  RELATIONSHIPS: "Relationships",
};

export const PRODUCT_TIMELINE_SOURCE_MODULE_LABELS: Record<
  ProductTimelineSourceModule,
  string
> = {
  PRODUCT_MANAGEMENT: "Product Management",
};
