/**
 * Purpose:
 * Configurable event categories, types, and source modules for Product Timeline.
 *
 * Implementation Package:
 * BP-003 / IP-001 – Product & Service Foundation
 */

export const PRODUCT_TIMELINE_EVENT_CATEGORIES = {
  REGISTRATION: "REGISTRATION",
  LIFECYCLE: "LIFECYCLE",
  GOVERNANCE: "GOVERNANCE",
  OPERATIONS: "OPERATIONS",
} as const;

export type ProductTimelineEventCategory =
  (typeof PRODUCT_TIMELINE_EVENT_CATEGORIES)[keyof typeof PRODUCT_TIMELINE_EVENT_CATEGORIES];

export const PRODUCT_TIMELINE_EVENT_TYPES = {
  /** IP-001 — active */
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_ACTIVATED: "PRODUCT_ACTIVATED",
  PRODUCT_SUSPENDED: "PRODUCT_SUSPENDED",
  PRODUCT_ARCHIVED: "PRODUCT_ARCHIVED",
  /** IP-002 — classification */
  CLASSIFICATION_CREATED: "CLASSIFICATION_CREATED",
  CLASSIFICATION_UPDATED: "CLASSIFICATION_UPDATED",
  CLASSIFICATION_MOVED: "CLASSIFICATION_MOVED",
  PRODUCT_ASSIGNED: "PRODUCT_ASSIGNED",
  PRODUCT_UNASSIGNED: "PRODUCT_UNASSIGNED",
  /** IP-003 — units of measure */
  UNIT_CREATED: "UNIT_CREATED",
  UNIT_UPDATED: "UNIT_UPDATED",
  UNIT_CONVERSION_CHANGED: "UNIT_CONVERSION_CHANGED",
  UNIT_ACTIVATED: "UNIT_ACTIVATED",
  UNIT_SUSPENDED: "UNIT_SUSPENDED",
  UNIT_ARCHIVED: "UNIT_ARCHIVED",
  /** IP-004 — product attributes */
  ATTRIBUTE_ASSIGNED: "ATTRIBUTE_ASSIGNED",
  ATTRIBUTE_UPDATED: "ATTRIBUTE_UPDATED",
  ATTRIBUTE_REMOVED: "ATTRIBUTE_REMOVED",
  ATTRIBUTE_OPTION_CHANGED: "ATTRIBUTE_OPTION_CHANGED",
  /** IP-005 — product variants */
  VARIANT_CREATED: "VARIANT_CREATED",
  VARIANT_UPDATED: "VARIANT_UPDATED",
  VARIANT_CLONED: "VARIANT_CLONED",
  VARIANT_ACTIVATED: "VARIANT_ACTIVATED",
  VARIANT_SUSPENDED: "VARIANT_SUSPENDED",
  VARIANT_ARCHIVED: "VARIANT_ARCHIVED",
  ATTRIBUTE_OVERRIDE_UPDATED: "ATTRIBUTE_OVERRIDE_UPDATED",
  /** IP-006 — product bundles */
  BUNDLE_CREATED: "BUNDLE_CREATED",
  BUNDLE_UPDATED: "BUNDLE_UPDATED",
  BUNDLE_ACTIVATED: "BUNDLE_ACTIVATED",
  BUNDLE_SUSPENDED: "BUNDLE_SUSPENDED",
  BUNDLE_ARCHIVED: "BUNDLE_ARCHIVED",
  BUNDLE_ITEM_ADDED: "BUNDLE_ITEM_ADDED",
  BUNDLE_ITEM_REMOVED: "BUNDLE_ITEM_REMOVED",
  BUNDLE_ITEM_QUANTITY_CHANGED: "BUNDLE_ITEM_QUANTITY_CHANGED",
  /** IP-007 — digital catalogue */
  PRODUCT_PUBLISHED: "PRODUCT_PUBLISHED",
  PRODUCT_UNPUBLISHED: "PRODUCT_UNPUBLISHED",
  CATALOGUE_VISIBILITY_CHANGED: "CATALOGUE_VISIBILITY_CHANGED",
  CATALOGUE_CHANNEL_ADDED: "CATALOGUE_CHANNEL_ADDED",
  CATALOGUE_CHANNEL_REMOVED: "CATALOGUE_CHANNEL_REMOVED",
  CATALOGUE_FEATURED_CHANGED: "CATALOGUE_FEATURED_CHANGED",
  CATALOGUE_SCHEDULE_CHANGED: "CATALOGUE_SCHEDULE_CHANGED",
  /** Future IPs — reserved taxonomy (append-only; no schema change required) */
  PRODUCT_PRICE_CHANGED: "PRODUCT_PRICE_CHANGED",
  PRODUCT_OWNER_CHANGED: "PRODUCT_OWNER_CHANGED",
  PRODUCT_STATUS_CHANGED: "PRODUCT_STATUS_CHANGED",
  PRODUCT_ATTRIBUTE_ADDED: "PRODUCT_ATTRIBUTE_ADDED",
  PRODUCT_BUNDLE_ADDED: "PRODUCT_BUNDLE_ADDED",
  PRODUCT_DOCUMENT_UPLOADED: "PRODUCT_DOCUMENT_UPLOADED",
} as const;

export type ProductTimelineEventType =
  (typeof PRODUCT_TIMELINE_EVENT_TYPES)[keyof typeof PRODUCT_TIMELINE_EVENT_TYPES];

export const PRODUCT_TIMELINE_SOURCE_MODULES = {
  PRODUCT_MANAGEMENT: "PRODUCT_MANAGEMENT",
} as const;

export type ProductTimelineSourceModule =
  (typeof PRODUCT_TIMELINE_SOURCE_MODULES)[keyof typeof PRODUCT_TIMELINE_SOURCE_MODULES];

export const PRODUCT_TIMELINE_VISIBILITY = {
  STANDARD: "STANDARD",
  INTERNAL: "INTERNAL",
  RESTRICTED: "RESTRICTED",
} as const;

export type ProductTimelineVisibility =
  (typeof PRODUCT_TIMELINE_VISIBILITY)[keyof typeof PRODUCT_TIMELINE_VISIBILITY];

export const PRODUCT_TIMELINE_DEFAULT_PAGE_SIZE = 20;

export const PRODUCT_TIMELINE_CATEGORY_LABELS: Record<
  ProductTimelineEventCategory,
  string
> = {
  REGISTRATION: "Registration",
  LIFECYCLE: "Lifecycle",
  GOVERNANCE: "Governance",
  OPERATIONS: "Operations",
};

export const PRODUCT_TIMELINE_SOURCE_MODULE_LABELS: Record<
  ProductTimelineSourceModule,
  string
> = {
  PRODUCT_MANAGEMENT: "Product Management",
};
