/**
 * Purpose:
 * Constants for Catalogue Structure Timeline (classification-scoped).
 *
 * Implementation Package:
 * BP-003 / IP-002 – Product Classification & Categorization
 */

export const CLASSIFICATION_TIMELINE_EVENT_CATEGORIES = {
  REGISTRATION: "REGISTRATION",
  LIFECYCLE: "LIFECYCLE",
  GOVERNANCE: "GOVERNANCE",
  OPERATIONS: "OPERATIONS",
} as const;

export type ClassificationTimelineEventCategory =
  (typeof CLASSIFICATION_TIMELINE_EVENT_CATEGORIES)[keyof typeof CLASSIFICATION_TIMELINE_EVENT_CATEGORIES];

export const CLASSIFICATION_TIMELINE_EVENT_TYPES = {
  CLASSIFICATION_CREATED: "CLASSIFICATION_CREATED",
  CLASSIFICATION_UPDATED: "CLASSIFICATION_UPDATED",
  CLASSIFICATION_MOVED: "CLASSIFICATION_MOVED",
  CLASSIFICATION_ACTIVATED: "CLASSIFICATION_ACTIVATED",
  CLASSIFICATION_SUSPENDED: "CLASSIFICATION_SUSPENDED",
  CLASSIFICATION_ARCHIVED: "CLASSIFICATION_ARCHIVED",
  CLASSIFICATION_DEPRECATED: "CLASSIFICATION_DEPRECATED",
  PRODUCT_ASSIGNED: "PRODUCT_ASSIGNED",
  PRODUCT_UNASSIGNED: "PRODUCT_UNASSIGNED",
} as const;

export type ClassificationTimelineEventType =
  (typeof CLASSIFICATION_TIMELINE_EVENT_TYPES)[keyof typeof CLASSIFICATION_TIMELINE_EVENT_TYPES];

export const CLASSIFICATION_TIMELINE_SOURCE_MODULES = {
  CATALOGUE_STRUCTURE: "CATALOGUE_STRUCTURE",
} as const;

export const CLASSIFICATION_TIMELINE_VISIBILITY = {
  STANDARD: "STANDARD",
} as const;

export const CLASSIFICATION_TIMELINE_DEFAULT_PAGE_SIZE = 20;
