/**
 * Purpose:
 * Constants for Attribute Definition Timeline.
 *
 * Implementation Package:
 * BP-003 / IP-004 – Product Attributes Engine
 */

export const ATTRIBUTE_TIMELINE_EVENT_CATEGORIES = {
  REGISTRATION: "REGISTRATION",
  CONFIGURATION: "CONFIGURATION",
  ASSIGNMENT: "ASSIGNMENT",
  LIFECYCLE: "LIFECYCLE",
} as const;

export type AttributeTimelineEventCategory =
  (typeof ATTRIBUTE_TIMELINE_EVENT_CATEGORIES)[keyof typeof ATTRIBUTE_TIMELINE_EVENT_CATEGORIES];

export const ATTRIBUTE_TIMELINE_EVENT_TYPES = {
  ATTRIBUTE_GROUP_CREATED: "ATTRIBUTE_GROUP_CREATED",
  ATTRIBUTE_GROUP_UPDATED: "ATTRIBUTE_GROUP_UPDATED",
  ATTRIBUTE_GROUP_ARCHIVED: "ATTRIBUTE_GROUP_ARCHIVED",
  ATTRIBUTE_CREATED: "ATTRIBUTE_CREATED",
  ATTRIBUTE_UPDATED: "ATTRIBUTE_UPDATED",
  ATTRIBUTE_ARCHIVED: "ATTRIBUTE_ARCHIVED",
  ATTRIBUTE_ASSIGNED: "ATTRIBUTE_ASSIGNED",
  ATTRIBUTE_REMOVED: "ATTRIBUTE_REMOVED",
  VALIDATION_CHANGED: "VALIDATION_CHANGED",
  ATTRIBUTE_OPTION_ADDED: "ATTRIBUTE_OPTION_ADDED",
  ATTRIBUTE_OPTION_CHANGED: "ATTRIBUTE_OPTION_CHANGED",
  ATTRIBUTE_OPTION_REMOVED: "ATTRIBUTE_OPTION_REMOVED",
} as const;

export type AttributeTimelineEventType =
  (typeof ATTRIBUTE_TIMELINE_EVENT_TYPES)[keyof typeof ATTRIBUTE_TIMELINE_EVENT_TYPES];

export const ATTRIBUTE_TIMELINE_SOURCE_MODULES = {
  PRODUCT_ATTRIBUTES: "PRODUCT_ATTRIBUTES",
} as const;

export const ATTRIBUTE_TIMELINE_VISIBILITY = {
  STANDARD: "STANDARD",
} as const;

export const ATTRIBUTE_TIMELINE_DEFAULT_PAGE_SIZE = 20;

export const ATTRIBUTE_TIMELINE_EVENT_TYPE_LABELS: Record<
  AttributeTimelineEventType,
  string
> = {
  ATTRIBUTE_GROUP_CREATED: "Attribute group created",
  ATTRIBUTE_GROUP_UPDATED: "Attribute group updated",
  ATTRIBUTE_GROUP_ARCHIVED: "Attribute group archived",
  ATTRIBUTE_CREATED: "Attribute created",
  ATTRIBUTE_UPDATED: "Attribute updated",
  ATTRIBUTE_ARCHIVED: "Attribute archived",
  ATTRIBUTE_ASSIGNED: "Attribute assigned",
  ATTRIBUTE_REMOVED: "Attribute removed",
  VALIDATION_CHANGED: "Validation changed",
  ATTRIBUTE_OPTION_ADDED: "Option added",
  ATTRIBUTE_OPTION_CHANGED: "Option changed",
  ATTRIBUTE_OPTION_REMOVED: "Option removed",
};
