/**
 * Purpose:
 * BP-007 IP-01 constants — obligation status, catalogues, idempotency.
 * Provider/rail/channel names are not encoded as routing keys.
 *
 * Implementation Package:
 * BP-007 / IP-01 – Payment Obligation & Provider Integration Foundation
 */

export const PAYMENTS_BUILD_PACK = "BP-007";
export const PAYMENTS_IP = "IP-01";
export const PAYMENTS_IP_02 = "IP-02";
export const PAYMENTS_IP_03 = "IP-03";
export const PAYMENTS_IP_04 = "IP-04";
export const PAYMENTS_IP_05 = "IP-05";
export const PAYMENTS_IP_06 = "IP-06";
export const PAYMENTS_IP_07 = "IP-07";
export const PAYMENTS_IP_08 = "IP-08";

export const PAYMENT_OBLIGATION_NUMBER_PREFIX = "POB";
export const PAYMENT_TRANSACTION_NUMBER_PREFIX = "PT";
export const PAYMENT_ALLOCATION_NUMBER_PREFIX = "AL";

export const PAYMENT_STATUS_CODES = {
  NOT_STARTED: "NOT_STARTED",
  INITIATED: "INITIATED",
  PENDING: "PENDING",
  SUCCESSFUL: "SUCCESSFUL",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
  UNKNOWN: "UNKNOWN",
} as const;

export type PaymentStatusCode =
  (typeof PAYMENT_STATUS_CODES)[keyof typeof PAYMENT_STATUS_CODES];

export const PAYMENT_IP01_STATUS = PAYMENT_STATUS_CODES.NOT_STARTED;

export const PAYMENT_CAPTURE_MODES = {
  ELECTRONIC: "ELECTRONIC",
  MANUAL: "MANUAL",
} as const;

export type PaymentCaptureMode =
  (typeof PAYMENT_CAPTURE_MODES)[keyof typeof PAYMENT_CAPTURE_MODES];

export const PAYMENT_FINANCIAL_INSTRUCTION_TYPES = {
  SALE: "SALE",
} as const;

export const PAYMENT_IDEMPOTENCY_OPERATIONS = {
  CREATE_OBLIGATION: "CREATE_OBLIGATION",
  INITIATE_PAYMENT: "INITIATE_PAYMENT",
  ALLOCATE_PAYMENT: "ALLOCATE_PAYMENT",
  ADJUST_ALLOCATION: "ADJUST_ALLOCATION",
  CREATE_INVOICE: "CREATE_INVOICE",
  ISSUE_INVOICE: "ISSUE_INVOICE",
  CANCEL_INVOICE: "CANCEL_INVOICE",
  CREATE_RECEIPT: "CREATE_RECEIPT",
  DELIVER_RECEIPT: "DELIVER_RECEIPT",
  REQUEST_REFUND: "REQUEST_REFUND",
  APPROVE_REFUND: "APPROVE_REFUND",
  INITIATE_REFUND: "INITIATE_REFUND",
  TRACK_SETTLEMENT: "TRACK_SETTLEMENT",
  APPLY_SETTLEMENT: "APPLY_SETTLEMENT",
  RAISE_EXCEPTION: "RAISE_EXCEPTION",
  RESOLVE_EXCEPTION: "RESOLVE_EXCEPTION",
  QUERY_PAYMENT_STATUS: "QUERY_PAYMENT_STATUS",
  RETRY_PAYMENT: "RETRY_PAYMENT",
} as const;

export const INVOICE_STATUS = {
  DRAFT: "DRAFT",
  ISSUED: "ISSUED",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
  OVERDUE: "OVERDUE",
  CANCELLED: "CANCELLED",
  CREDITED: "CREDITED",
} as const;

export type InvoiceStatus = (typeof INVOICE_STATUS)[keyof typeof INVOICE_STATUS];

export const INVOICE_STATUS_LABELS: Record<string, string> = {
  DRAFT: "Draft",
  ISSUED: "Issued",
  PARTIALLY_PAID: "Part paid",
  PAID: "Paid",
  OVERDUE: "Overdue",
  CANCELLED: "Cancelled",
  CREDITED: "Credited",
};

export const INVOICE_ADJUSTMENT_TYPES = {
  CREDIT_NOTE: "CREDIT_NOTE",
} as const;

export const PAYMENT_ALLOCATION_STATUS = {
  ALLOCATED: "ALLOCATED",
  ADJUSTED: "ADJUSTED",
  REFUND: "REFUND",
} as const;

export type PaymentAllocationStatus =
  (typeof PAYMENT_ALLOCATION_STATUS)[keyof typeof PAYMENT_ALLOCATION_STATUS];

export const PAYMENT_ALLOCATION_TARGET = {
  OBLIGATION: "OBLIGATION",
} as const;

export const PAYMENT_AUDIT_ACTIONS = {
  OBLIGATION_CREATED: "OBLIGATION_CREATED",
  OBLIGATION_CREATE_FAILED: "OBLIGATION_CREATE_FAILED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_MANUAL_CAPTURED: "PAYMENT_MANUAL_CAPTURED",
  PAYMENT_STATUS_CHANGED: "PAYMENT_STATUS_CHANGED",
  PAYMENT_SUCCESSFUL: "PAYMENT_SUCCESSFUL",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  PROVIDER_REFERENCE_ASSIGNED: "PROVIDER_REFERENCE_ASSIGNED",
  PAYMENT_OUTCOME_RECEIVED: "PAYMENT_OUTCOME_RECEIVED",
  ALLOCATION_CREATED: "ALLOCATION_CREATED",
  ALLOCATION_ADJUSTED: "ALLOCATION_ADJUSTED",
  UNALLOCATED_BALANCE_RECORDED: "UNALLOCATED_BALANCE_RECORDED",
  OBLIGATION_BALANCE_UPDATED: "OBLIGATION_BALANCE_UPDATED",
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_ISSUED: "INVOICE_ISSUED",
  INVOICE_STATUS_CHANGED: "INVOICE_STATUS_CHANGED",
  INVOICE_CANCELLED: "INVOICE_CANCELLED",
  INVOICE_OVERDUE: "INVOICE_OVERDUE",
  INVOICE_DOCUMENT_REQUESTED: "INVOICE_DOCUMENT_REQUESTED",
  INVOICE_CREDIT_LINKAGE_CREATED: "INVOICE_CREDIT_LINKAGE_CREATED",
  INVOICE_ALLOCATION_REFLECTED: "INVOICE_ALLOCATION_REFLECTED",
  RECEIPT_CREATED: "RECEIPT_CREATED",
  RECEIPT_ISSUED: "RECEIPT_ISSUED",
  RECEIPT_DOCUMENT_REQUESTED: "RECEIPT_DOCUMENT_REQUESTED",
  RECEIPT_DELIVERY_REQUESTED: "RECEIPT_DELIVERY_REQUESTED",
  RECEIPT_DELIVERY_FAILED: "RECEIPT_DELIVERY_FAILED",
  RECEIPT_VIEWED: "RECEIPT_VIEWED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUND_APPROVAL_REQUESTED: "REFUND_APPROVAL_REQUESTED",
  REFUND_APPROVED: "REFUND_APPROVED",
  REFUND_REJECTED: "REFUND_REJECTED",
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUND_PENDING: "REFUND_PENDING",
  REFUND_SUCCESSFUL: "REFUND_SUCCESSFUL",
  REFUND_FAILED: "REFUND_FAILED",
  REFUND_UNKNOWN: "REFUND_UNKNOWN",
  REFUND_DOCUMENT_REQUESTED: "REFUND_DOCUMENT_REQUESTED",
  SETTLEMENT_CREATED: "SETTLEMENT_CREATED",
  SETTLEMENT_PENDING: "SETTLEMENT_PENDING",
  SETTLEMENT_RECEIVED: "SETTLEMENT_RECEIVED",
  SETTLEMENT_CONFIRMED: "SETTLEMENT_CONFIRMED",
  SETTLEMENT_EXCEPTION: "SETTLEMENT_EXCEPTION",
  SETTLEMENT_UPDATED: "SETTLEMENT_UPDATED",
  PAYMENT_EXCEPTION_CREATED: "PAYMENT_EXCEPTION_CREATED",
  PAYMENT_EXCEPTION_OPENED: "PAYMENT_EXCEPTION_OPENED",
  PAYMENT_EXCEPTION_INVESTIGATION_STARTED: "PAYMENT_EXCEPTION_INVESTIGATION_STARTED",
  PAYMENT_EXCEPTION_QUERY_REQUESTED: "PAYMENT_EXCEPTION_QUERY_REQUESTED",
  PAYMENT_EXCEPTION_RETRY_REQUESTED: "PAYMENT_EXCEPTION_RETRY_REQUESTED",
  PAYMENT_EXCEPTION_RETRY_APPROVED: "PAYMENT_EXCEPTION_RETRY_APPROVED",
  PAYMENT_EXCEPTION_RESOLVED: "PAYMENT_EXCEPTION_RESOLVED",
  PAYMENT_EXCEPTION_REJECTED: "PAYMENT_EXCEPTION_REJECTED",
  PAYMENT_EXCEPTION_CLOSED: "PAYMENT_EXCEPTION_CLOSED",
} as const;

export type PaymentAuditAction =
  (typeof PAYMENT_AUDIT_ACTIONS)[keyof typeof PAYMENT_AUDIT_ACTIONS];

export const PAYMENT_INELIGIBLE_ORDER_STATUSES = [
  "DRAFT",
  "SUBMITTED_FOR_CONFIRMATION",
  "CANCELLED",
] as const;

export const CREDIT_ENABLEMENT_FLAG = "creditSalesEnabled";

export const RECEIPT_STATUS = {
  ISSUED: "ISSUED",
} as const;

export type ReceiptStatus = (typeof RECEIPT_STATUS)[keyof typeof RECEIPT_STATUS];

export const RECEIPT_STATUS_LABELS: Record<string, string> = {
  ISSUED: "Issued",
};

export const REFUND_STATUS = {
  REQUESTED: "REQUESTED",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  INITIATED: "INITIATED",
  PENDING: "PENDING",
  SUCCESSFUL: "SUCCESSFUL",
  FAILED: "FAILED",
  UNKNOWN: "UNKNOWN",
} as const;

export type RefundStatus = (typeof REFUND_STATUS)[keyof typeof REFUND_STATUS];

export const REFUND_STATUS_LABELS: Record<string, string> = {
  REQUESTED: "Refund requested",
  APPROVAL_PENDING: "Pending approval",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  INITIATED: "Refund processing",
  PENDING: "Refund processing",
  SUCCESSFUL: "Refund successful",
  FAILED: "Refund failed",
  UNKNOWN: "Refund requires investigation",
};

export const REFUND_TYPES = {
  FULL_REFUND: "FULL_REFUND",
  PARTIAL_REFUND: "PARTIAL_REFUND",
  REVERSAL: "REVERSAL",
} as const;

export type RefundType = (typeof REFUND_TYPES)[keyof typeof REFUND_TYPES];

export const REFUND_TYPE_LABELS: Record<string, string> = {
  FULL_REFUND: "Full",
  PARTIAL_REFUND: "Partial",
  REVERSAL: "Reversal",
};

export const REFUND_IN_FLIGHT_STATUSES = new Set<string>([
  REFUND_STATUS.REQUESTED,
  REFUND_STATUS.APPROVAL_PENDING,
  REFUND_STATUS.APPROVED,
  REFUND_STATUS.INITIATED,
  REFUND_STATUS.PENDING,
  REFUND_STATUS.UNKNOWN,
]);

export const SETTLEMENT_STATUS = {
  NOT_APPLICABLE: "NOT_APPLICABLE",
  SETTLEMENT_PENDING: "SETTLEMENT_PENDING",
  SETTLEMENT_RECEIVED: "SETTLEMENT_RECEIVED",
  SETTLEMENT_CONFIRMED: "SETTLEMENT_CONFIRMED",
  SETTLEMENT_EXCEPTION: "SETTLEMENT_EXCEPTION",
} as const;

export type SettlementStatus = (typeof SETTLEMENT_STATUS)[keyof typeof SETTLEMENT_STATUS];

export const SETTLEMENT_STATUS_LABELS: Record<string, string> = {
  NOT_APPLICABLE: "Not applicable",
  SETTLEMENT_PENDING: "Settlement pending",
  SETTLEMENT_RECEIVED: "Settlement received",
  SETTLEMENT_CONFIRMED: "Settlement confirmed",
  SETTLEMENT_EXCEPTION: "Settlement exception",
};

export const SETTLEMENT_MODES = {
  NOT_APPLICABLE: "NOT_APPLICABLE",
  IMMEDIATE: "IMMEDIATE",
  PROVIDER: "PROVIDER",
} as const;

export const PAYMENT_EXCEPTION_TYPES = {
  PAYMENT_UNKNOWN: "PAYMENT_UNKNOWN",
  PAYMENT_TIMEOUT: "PAYMENT_TIMEOUT",
  CALLBACK_AMOUNT_MISMATCH: "CALLBACK_AMOUNT_MISMATCH",
  CALLBACK_CURRENCY_MISMATCH: "CALLBACK_CURRENCY_MISMATCH",
  CALLBACK_OBLIGATION_MISMATCH: "CALLBACK_OBLIGATION_MISMATCH",
  DUPLICATE_PROVIDER_REFERENCE: "DUPLICATE_PROVIDER_REFERENCE",
  PROVIDER_FAILURE: "PROVIDER_FAILURE",
  PROVIDER_RESPONSE_CONFLICT: "PROVIDER_RESPONSE_CONFLICT",
  SETTLEMENT_VARIANCE: "SETTLEMENT_VARIANCE",
  OTHER_PAYMENT_EXCEPTION: "OTHER_PAYMENT_EXCEPTION",
} as const;

export type PaymentExceptionType =
  (typeof PAYMENT_EXCEPTION_TYPES)[keyof typeof PAYMENT_EXCEPTION_TYPES];

export const PAYMENT_EXCEPTION_TYPE_LABELS: Record<string, string> = {
  PAYMENT_UNKNOWN: "Payment confirmation unknown",
  PAYMENT_TIMEOUT: "No confirmation received in time",
  CALLBACK_AMOUNT_MISMATCH: "Confirmed amount does not match",
  CALLBACK_CURRENCY_MISMATCH: "Confirmed currency does not match",
  CALLBACK_OBLIGATION_MISMATCH: "Confirmation does not match this payment",
  DUPLICATE_PROVIDER_REFERENCE: "Duplicate provider reference",
  PROVIDER_FAILURE: "Provider reported a failure",
  PROVIDER_RESPONSE_CONFLICT: "Provider confirmation conflicts",
  SETTLEMENT_VARIANCE: "Settlement amount differs",
  OTHER_PAYMENT_EXCEPTION: "Needs review",
};

export const PAYMENT_EXCEPTION_STATUSES = {
  OPEN: "OPEN",
  INVESTIGATING: "INVESTIGATING",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
  CLOSED: "CLOSED",
} as const;

export type PaymentExceptionStatus =
  (typeof PAYMENT_EXCEPTION_STATUSES)[keyof typeof PAYMENT_EXCEPTION_STATUSES];

export const PAYMENT_EXCEPTION_STATUS_LABELS: Record<string, string> = {
  OPEN: "Open",
  INVESTIGATING: "Investigating",
  RESOLVED: "Resolved",
  REJECTED: "Rejected",
  CLOSED: "Closed",
};

export const PAYMENT_EXCEPTION_SEVERITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;

export const PAYMENT_EXCEPTION_RESOLUTION_CODES = {
  CONFIRMED_SUCCESS: "CONFIRMED_SUCCESS",
  CONFIRMED_FAILURE: "CONFIRMED_FAILURE",
  EXPIRED: "EXPIRED",
  DUPLICATE: "DUPLICATE",
  INVALID_CALLBACK: "INVALID_CALLBACK",
  CUSTOMER_ACTION_REQUIRED: "CUSTOMER_ACTION_REQUIRED",
  PROVIDER_CONFIRMED_NOT_ACCEPTED: "PROVIDER_CONFIRMED_NOT_ACCEPTED",
  OTHER: "OTHER",
} as const;

export const PAYMENT_EXCEPTION_RESOLUTION_LABELS: Record<string, string> = {
  CONFIRMED_SUCCESS: "Confirmed successful",
  CONFIRMED_FAILURE: "Confirmed failed",
  EXPIRED: "Expired",
  DUPLICATE: "Duplicate",
  INVALID_CALLBACK: "Invalid confirmation",
  CUSTOMER_ACTION_REQUIRED: "Customer action required",
  PROVIDER_CONFIRMED_NOT_ACCEPTED: "Provider confirmed not accepted",
  OTHER: "Other",
};

export const RECEIPT_DELIVERY_STATUS_LABELS: Record<string, string> = {
  NONE: "Not sent",
  REQUESTED: "Send requested",
  DELIVERED: "Sent",
  FAILED: "Send failed",
};

export const PAYMENT_STATUS_LABELS: Record<string, string> = {
  NOT_STARTED: "Not started",
  INITIATED: "Payment request sent",
  PENDING: "Payment is still being processed",
  SUCCESSFUL: "Payment successful",
  FAILED: "Payment failed",
  EXPIRED: "Payment expired",
  UNKNOWN: "Payment needs review",
};

export const PAYMENT_CUSTOMER_STATUS_MESSAGES: Record<string, string> = {
  NOT_STARTED: "Payment has not started yet.",
  INITIATED: "Payment request sent. Waiting for confirmation…",
  PENDING: "Payment is still being processed.",
  SUCCESSFUL: "Payment successful.",
  FAILED: "Payment failed.",
  EXPIRED: "This payment request has expired.",
  UNKNOWN: "Payment confirmation is not available yet. Do not send another payment.",
};
