/**
 * Purpose:
 * ENG-005 Workflow Engine identifiers. Refund maker-checker slice only.
 *
 * Engine:
 * ENG-005 – Workflow & Approval Engine
 */

export const WORKFLOW_ENGINE_ID = "ENG-005";

export const WORKFLOW_OPERATIONS = {
  REFUND_APPROVAL: "REFUND_APPROVAL",
  EXCEPTION_RESOLUTION: "EXCEPTION_RESOLUTION",
  OPERATION_APPROVAL: "OPERATION_APPROVAL",
  PURCHASE_REQUEST_APPROVAL: "PURCHASE_REQUEST_APPROVAL",
  SOURCING_EXTENSION_APPROVAL: "SOURCING_EXTENSION_APPROVAL",
  SOURCING_OPENING_APPROVAL: "SOURCING_OPENING_APPROVAL",
  SOURCING_AWARD_APPROVAL: "SOURCING_AWARD_APPROVAL",
  PURCHASE_ORDER_APPROVAL: "PURCHASE_ORDER_APPROVAL",
  CONTRACT_APPROVAL: "CONTRACT_APPROVAL",
  CONTRACT_AMENDMENT_APPROVAL: "CONTRACT_AMENDMENT_APPROVAL",
} as const;
