/**
 * Purpose:
 * BP-008 IP-01 constants — item types, location types, audit actions.
 * UOM codes are not encoded as transaction routing keys.
 *
 * Implementation Package:
 * BP-008 / IP-01 – Inventory Foundation & Stock Item Master
 */

export const INVENTORY_BUILD_PACK = "BP-008";
export const INVENTORY_IP = "IP-01";

export const STOCK_ITEM_TYPE_CODES = {
  STOCKED_ITEM: "STOCKED_ITEM",
  NON_STOCK_ITEM: "NON_STOCK_ITEM",
} as const;

export type StockItemTypeCode =
  (typeof STOCK_ITEM_TYPE_CODES)[keyof typeof STOCK_ITEM_TYPE_CODES];

export const STOCK_ITEM_TYPE_LABELS: Record<StockItemTypeCode, string> = {
  STOCKED_ITEM: "Stocked item",
  NON_STOCK_ITEM: "Non-stock item",
};

export const INVENTORY_LOCATION_TYPE_CODES = {
  MAIN_STORE: "MAIN_STORE",
  SHOP_FLOOR: "SHOP_FLOOR",
  WAREHOUSE: "WAREHOUSE",
  BRANCH_STORE: "BRANCH_STORE",
  BACK_STORE: "BACK_STORE",
} as const;

export type InventoryLocationTypeCode =
  (typeof INVENTORY_LOCATION_TYPE_CODES)[keyof typeof INVENTORY_LOCATION_TYPE_CODES];

export const INVENTORY_LOCATION_TYPE_LABELS: Record<
  InventoryLocationTypeCode,
  string
> = {
  MAIN_STORE: "Main store",
  SHOP_FLOOR: "Shop floor",
  WAREHOUSE: "Warehouse",
  BRANCH_STORE: "Branch store",
  BACK_STORE: "Back store",
};

export const PRODUCT_TYPES_THAT_CANNOT_CREATE_STOCK = [
  "SERVICE",
  "DIGITAL_PRODUCT",
  "SUBSCRIPTION",
  "MEMBERSHIP",
  "INSURANCE",
  "LOAN_PRODUCT",
  "COURSE",
] as const;

export const INVENTORY_AUDIT_ACTIONS = {
  STOCK_ITEM_CREATED: "STOCK_ITEM_CREATED",
  STOCK_ITEM_UPDATED: "STOCK_ITEM_UPDATED",
  STOCK_ITEM_ACTIVATED: "STOCK_ITEM_ACTIVATED",
  STOCK_ITEM_DEACTIVATED: "STOCK_ITEM_DEACTIVATED",
  INVENTORY_LOCATION_CREATED: "INVENTORY_LOCATION_CREATED",
  INVENTORY_LOCATION_UPDATED: "INVENTORY_LOCATION_UPDATED",
  INVENTORY_LOCATION_ACTIVATED: "INVENTORY_LOCATION_ACTIVATED",
  INVENTORY_LOCATION_DEACTIVATED: "INVENTORY_LOCATION_DEACTIVATED",
  STOCK_ITEM_LOCATION_CONFIGURED: "STOCK_ITEM_LOCATION_CONFIGURED",
  STOCK_ITEM_LOCATION_UPDATED: "STOCK_ITEM_LOCATION_UPDATED",
  OPENING_STOCK_RECORDED: "OPENING_STOCK_RECORDED",
  RECEIPT_CREATED: "RECEIPT_CREATED",
  RECEIPT_SUBMITTED: "RECEIPT_SUBMITTED",
  RECEIPT_APPROVED: "RECEIPT_APPROVED",
  RECEIPT_REJECTED: "RECEIPT_REJECTED",
  RECEIPT_POSTED: "RECEIPT_POSTED",
  RECEIPT_CANCELLED: "RECEIPT_CANCELLED",
  OPENING_BALANCE_CREATED: "OPENING_BALANCE_CREATED",
  OPENING_BALANCE_SUBMITTED: "OPENING_BALANCE_SUBMITTED",
  OPENING_BALANCE_APPROVED: "OPENING_BALANCE_APPROVED",
  OPENING_BALANCE_REJECTED: "OPENING_BALANCE_REJECTED",
  OPENING_BALANCE_POSTED: "OPENING_BALANCE_POSTED",
  OPENING_BALANCE_CANCELLED: "OPENING_BALANCE_CANCELLED",
  STOCK_RESERVATION_REQUESTED: "STOCK_RESERVATION_REQUESTED",
  STOCK_RESERVED: "STOCK_RESERVED",
  STOCK_RESERVATION_APPROVED: "STOCK_RESERVATION_APPROVED",
  STOCK_RESERVATION_REJECTED: "STOCK_RESERVATION_REJECTED",
  STOCK_RESERVATION_RELEASED: "STOCK_RESERVATION_RELEASED",
  STOCK_RESERVATION_EXPIRED: "STOCK_RESERVATION_EXPIRED",
  STOCK_RESERVATION_PARTIALLY_FULFILLED: "STOCK_RESERVATION_PARTIALLY_FULFILLED",
  STOCK_RESERVATION_FULFILLED: "STOCK_RESERVATION_FULFILLED",
  STOCK_DEDUCTION_REQUESTED: "STOCK_DEDUCTION_REQUESTED",
  STOCK_DEDUCTED: "STOCK_DEDUCTED",
  STOCK_DEDUCTION_REJECTED: "STOCK_DEDUCTION_REJECTED",
  STOCK_DEDUCTION_IDEMPOTENT: "STOCK_DEDUCTION_IDEMPOTENT",
  ADJUSTMENT_CREATED: "ADJUSTMENT_CREATED",
  ADJUSTMENT_SUBMITTED: "ADJUSTMENT_SUBMITTED",
  ADJUSTMENT_APPROVAL_REQUESTED: "ADJUSTMENT_APPROVAL_REQUESTED",
  ADJUSTMENT_APPROVED: "ADJUSTMENT_APPROVED",
  ADJUSTMENT_REJECTED: "ADJUSTMENT_REJECTED",
  ADJUSTMENT_POSTED: "ADJUSTMENT_POSTED",
  ADJUSTMENT_CANCELLED: "ADJUSTMENT_CANCELLED",
  DAMAGE_RECORDED: "DAMAGE_RECORDED",
  LOSS_RECORDED: "LOSS_RECORDED",
  CUSTOMER_RETURN_POSTED: "CUSTOMER_RETURN_POSTED",
  SUPPLIER_RETURN_POSTED: "SUPPLIER_RETURN_POSTED",
  STOCKTAKE_CREATED: "STOCKTAKE_CREATED",
  STOCKTAKE_STARTED: "STOCKTAKE_STARTED",
  STOCKTAKE_COUNT_RECORDED: "STOCKTAKE_COUNT_RECORDED",
  STOCKTAKE_RECOUNT_RECORDED: "STOCKTAKE_RECOUNT_RECORDED",
  STOCKTAKE_SUBMITTED: "STOCKTAKE_SUBMITTED",
  STOCKTAKE_APPROVAL_REQUESTED: "STOCKTAKE_APPROVAL_REQUESTED",
  STOCKTAKE_APPROVED: "STOCKTAKE_APPROVED",
  STOCKTAKE_REJECTED: "STOCKTAKE_REJECTED",
  STOCKTAKE_CANCELLED: "STOCKTAKE_CANCELLED",
  STOCKTAKE_RECONCILIATION_POSTED: "STOCKTAKE_RECONCILIATION_POSTED",
  STOCKTAKE_COMPLETED: "STOCKTAKE_COMPLETED",
  TRACKING_MODE_CHANGED: "TRACKING_MODE_CHANGED",
  LOT_CREATED: "LOT_CREATED",
  LOT_UPDATED: "LOT_UPDATED",
  TRACKED_UNIT_CREATED: "TRACKED_UNIT_CREATED",
  TRACKED_UNIT_ASSIGNED: "TRACKED_UNIT_ASSIGNED",
  TRACKED_UNIT_RESERVED: "TRACKED_UNIT_RESERVED",
  TRACKED_UNIT_RELEASED: "TRACKED_UNIT_RELEASED",
  TRACKED_UNIT_SOLD: "TRACKED_UNIT_SOLD",
  TRACKED_UNIT_ADJUSTED: "TRACKED_UNIT_ADJUSTED",
  CONTROL_SETTINGS_CREATED: "CONTROL_SETTINGS_CREATED",
  CONTROL_SETTINGS_CHANGED: "CONTROL_SETTINGS_CHANGED",
  CONTROL_CHANGE_SUBMITTED: "CONTROL_CHANGE_SUBMITTED",
  CONTROL_CHANGE_APPROVED: "CONTROL_CHANGE_APPROVED",
  CONTROL_CHANGE_REJECTED: "CONTROL_CHANGE_REJECTED",
  REPLENISHMENT_CONDITION_DETECTED: "REPLENISHMENT_CONDITION_DETECTED",
  REPLENISHMENT_ADVICE_CREATED: "REPLENISHMENT_ADVICE_CREATED",
  REPLENISHMENT_ADVICE_ACKNOWLEDGED: "REPLENISHMENT_ADVICE_ACKNOWLEDGED",
  REPLENISHMENT_ADVICE_CLOSED: "REPLENISHMENT_ADVICE_CLOSED",
  EXCEPTION_CREATED: "EXCEPTION_CREATED",
  EXCEPTION_OPENED: "EXCEPTION_OPENED",
  EXCEPTION_INVESTIGATING: "EXCEPTION_INVESTIGATING",
  EXCEPTION_QUERY: "EXCEPTION_QUERY",
  EXCEPTION_RESOLUTION_REQUESTED: "EXCEPTION_RESOLUTION_REQUESTED",
  EXCEPTION_APPROVED: "EXCEPTION_APPROVED",
  EXCEPTION_REJECTED: "EXCEPTION_REJECTED",
  EXCEPTION_RESOLVED: "EXCEPTION_RESOLVED",
  EXCEPTION_CLOSED: "EXCEPTION_CLOSED",
  TRANSFER_CREATED: "TRANSFER_CREATED",
  TRANSFER_REQUESTED: "TRANSFER_REQUESTED",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  TRANSFER_REJECTED: "TRANSFER_REJECTED",
  TRANSFER_DISPATCHED: "TRANSFER_DISPATCHED",
  TRANSFER_RECEIVED: "TRANSFER_RECEIVED",
  TRANSFER_DISCREPANCY: "TRANSFER_DISCREPANCY",
  TRANSFER_CANCELLED: "TRANSFER_CANCELLED",
  TRANSFER_COMPLETED: "TRANSFER_COMPLETED",
} as const;

export const INVENTORY_DOCUMENT_STATUSES = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  POSTED: "POSTED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
} as const;

export type InventoryDocumentStatus =
  (typeof INVENTORY_DOCUMENT_STATUSES)[keyof typeof INVENTORY_DOCUMENT_STATUSES];

export const INVENTORY_OPERATION_CODES = {
  STOCK_RECEIVING: "STOCK_RECEIVING",
  OPENING_BALANCE: "OPENING_BALANCE",
  STOCK_RESERVATION: "STOCK_RESERVATION",
  STOCK_DEDUCTION: "STOCK_DEDUCTION",
  STOCK_RESERVATION_RELEASE: "STOCK_RESERVATION_RELEASE",
  STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT",
  CUSTOMER_RETURN: "CUSTOMER_RETURN",
  SUPPLIER_RETURN: "SUPPLIER_RETURN",
  STOCKTAKE: "STOCKTAKE",
  INVENTORY_CONTROL_CONFIG: "INVENTORY_CONTROL_CONFIG",
  OPS_INCIDENT_RESOLUTION: "OPS_INCIDENT_RESOLUTION",
  STOCK_TRANSFER: "STOCK_TRANSFER",
} as const;

export type InventoryOperationCode =
  (typeof INVENTORY_OPERATION_CODES)[keyof typeof INVENTORY_OPERATION_CODES];

export const INVENTORY_OVER_RECEIPT_POLICIES = {
  BLOCK: "BLOCK",
  ALLOW_WITH_WARNING: "ALLOW_WITH_WARNING",
  ALLOW: "ALLOW",
} as const;

export type InventoryOverReceiptPolicy =
  (typeof INVENTORY_OVER_RECEIPT_POLICIES)[keyof typeof INVENTORY_OVER_RECEIPT_POLICIES];

export const INVENTORY_IDEMPOTENCY_OPERATIONS = {
  POST_RECEIPT: "POST_RECEIPT",
  POST_OPENING: "POST_OPENING",
  CREATE_RESERVATION: "CREATE_RESERVATION",
  FULFIL_RESERVATION: "FULFIL_RESERVATION",
  RELEASE_RESERVATION: "RELEASE_RESERVATION",
  CREATE_STOCK_ADJUSTMENT: "CREATE_STOCK_ADJUSTMENT",
  CREATE_CUSTOMER_RETURN: "CREATE_CUSTOMER_RETURN",
  POST_ADJUSTMENT: "POST_ADJUSTMENT",
  CREATE_STOCKTAKE: "CREATE_STOCKTAKE",
  POST_STOCKTAKE: "POST_STOCKTAKE",
  CAPTURE_LINE_TRACE: "CAPTURE_LINE_TRACE",
  SAVE_CONTROL_SETTINGS: "SAVE_CONTROL_SETTINGS",
  SYNC_REPLENISHMENT_ADVICE: "SYNC_REPLENISHMENT_ADVICE",
  ACKNOWLEDGE_ADVICE: "ACKNOWLEDGE_ADVICE",
  CLOSE_ADVICE: "CLOSE_ADVICE",
  RECORD_OPS_INCIDENT: "RECORD_OPS_INCIDENT",
  RESOLVE_OPS_INCIDENT: "RESOLVE_OPS_INCIDENT",
  CREATE_TRANSFER: "CREATE_TRANSFER",
  APPROVE_TRANSFER: "APPROVE_TRANSFER",
  REJECT_TRANSFER: "REJECT_TRANSFER",
  DISPATCH_TRANSFER: "DISPATCH_TRANSFER",
  RECEIVE_TRANSFER: "RECEIVE_TRANSFER",
  COMPLETE_TRANSFER: "COMPLETE_TRANSFER",
  CANCEL_TRANSFER: "CANCEL_TRANSFER",
} as const;

export const INVENTORY_TRACKING_MODES = {
  NONE: "NONE",
  BATCH: "BATCH",
  SERIAL: "SERIAL",
} as const;

export type InventoryTrackingMode =
  (typeof INVENTORY_TRACKING_MODES)[keyof typeof INVENTORY_TRACKING_MODES];

export const INVENTORY_LOT_STATUSES = {
  ACTIVE: "ACTIVE",
  CLOSED: "CLOSED",
} as const;

export const INVENTORY_TRACKED_UNIT_STATUSES = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  SOLD: "SOLD",
  DAMAGED: "DAMAGED",
  LOST: "LOST",
  RETURNED: "RETURNED",
} as const;

export const INVENTORY_EXPIRY_STATUSES = {
  NOT_EXPIRED: "NOT_EXPIRED",
  EXPIRING_SOON: "EXPIRING_SOON",
  EXPIRED: "EXPIRED",
} as const;

export const INVENTORY_ADJUSTMENT_TYPES = {
  POSITIVE_ADJUSTMENT: "POSITIVE_ADJUSTMENT",
  NEGATIVE_ADJUSTMENT: "NEGATIVE_ADJUSTMENT",
  DAMAGE: "DAMAGE",
  LOSS: "LOSS",
  CUSTOMER_RETURN: "CUSTOMER_RETURN",
  SUPPLIER_RETURN: "SUPPLIER_RETURN",
} as const;

export type InventoryAdjustmentType =
  (typeof INVENTORY_ADJUSTMENT_TYPES)[keyof typeof INVENTORY_ADJUSTMENT_TYPES];

export const INVENTORY_ADJUSTMENT_TYPE_LABELS: Record<InventoryAdjustmentType, string> = {
  POSITIVE_ADJUSTMENT: "Stock adjustment",
  NEGATIVE_ADJUSTMENT: "Stock adjustment",
  DAMAGE: "Damaged",
  LOSS: "Lost",
  CUSTOMER_RETURN: "Customer return",
  SUPPLIER_RETURN: "Supplier return",
};

export const INVENTORY_RETURN_CONDITIONS = {
  SALEABLE: "SALEABLE",
  DAMAGED: "DAMAGED",
  QUARANTINED: "QUARANTINED",
} as const;

export const INVENTORY_RESERVATION_STATUSES = {
  REQUESTED: "REQUESTED",
  RESERVED: "RESERVED",
  PARTIALLY_FULFILLED: "PARTIALLY_FULFILLED",
  FULFILLED: "FULFILLED",
  REJECTED: "REJECTED",
  RELEASED: "RELEASED",
  EXPIRED: "EXPIRED",
} as const;

export type InventoryReservationStatus =
  (typeof INVENTORY_RESERVATION_STATUSES)[keyof typeof INVENTORY_RESERVATION_STATUSES];

export const INVENTORY_STOCKTAKE_STATUSES = {
  DRAFT: "DRAFT",
  IN_PROGRESS: "IN_PROGRESS",
  SUBMITTED: "SUBMITTED",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  APPROVED: "APPROVED",
  POSTED: "POSTED",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
} as const;

export type InventoryStocktakeStatus =
  (typeof INVENTORY_STOCKTAKE_STATUSES)[keyof typeof INVENTORY_STOCKTAKE_STATUSES];

export const INVENTORY_STOCKTAKE_SCOPE_TYPES = {
  LOCATION: "LOCATION",
  ITEM: "ITEM",
  GROUP: "GROUP",
} as const;

export const INVENTORY_STOCKTAKE_LINE_STATUSES = {
  PENDING: "PENDING",
  COUNTED: "COUNTED",
  RECOUNTED: "RECOUNTED",
} as const;

export const INVENTORY_VARIANCE_CLASSES = {
  POSITIVE: "POSITIVE",
  NEGATIVE: "NEGATIVE",
  ZERO: "ZERO",
} as const;

export const INVENTORY_CONTROL_STATUSES = {
  HEALTHY: "HEALTHY",
  LOW_STOCK: "LOW_STOCK",
  REORDER_REQUIRED: "REORDER_REQUIRED",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  OVERSTOCK: "OVERSTOCK",
  CONFIGURATION_MISSING: "CONFIGURATION_MISSING",
} as const;

export type InventoryControlStatus =
  (typeof INVENTORY_CONTROL_STATUSES)[keyof typeof INVENTORY_CONTROL_STATUSES];

export const INVENTORY_CONTROL_STATUS_LABELS: Record<InventoryControlStatus, string> = {
  HEALTHY: "Healthy",
  LOW_STOCK: "Low stock",
  REORDER_REQUIRED: "Reorder required",
  OUT_OF_STOCK: "Out of stock",
  OVERSTOCK: "Overstock",
  CONFIGURATION_MISSING: "Configuration missing",
};

export const INVENTORY_ADVICE_STATUSES = {
  OPEN: "OPEN",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  CLOSED: "CLOSED",
} as const;

export type InventoryAdviceStatus =
  (typeof INVENTORY_ADVICE_STATUSES)[keyof typeof INVENTORY_ADVICE_STATUSES];

export const INVENTORY_CONTROL_CHANGE_STATUSES = {
  DRAFT: "DRAFT",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

export const INVENTORY_OPS_INCIDENT_TYPES = {
  RECEIVING_MISMATCH: "RECEIVING_MISMATCH",
  STOCK_NEGATIVE_ATTEMPT: "STOCK_NEGATIVE_ATTEMPT",
  RESERVATION_CONFLICT: "RESERVATION_CONFLICT",
  STOCKTAKE_VARIANCE: "STOCKTAKE_VARIANCE",
  ADJUSTMENT_REVIEW: "ADJUSTMENT_REVIEW",
  TRANSFER_EXCEPTION: "TRANSFER_EXCEPTION",
  BATCH_EXPIRY_EXCEPTION: "BATCH_EXPIRY_EXCEPTION",
  SERIAL_EXCEPTION: "SERIAL_EXCEPTION",
  DUPLICATE_OPERATION: "DUPLICATE_OPERATION",
  INVENTORY_DATA_INCONSISTENCY: "INVENTORY_DATA_INCONSISTENCY",
  CONTROL_CONFIGURATION_EXCEPTION: "CONTROL_CONFIGURATION_EXCEPTION",
} as const;

export type InventoryOpsIncidentTypeCode =
  (typeof INVENTORY_OPS_INCIDENT_TYPES)[keyof typeof INVENTORY_OPS_INCIDENT_TYPES];

export const INVENTORY_OPS_INCIDENT_TYPE_LABELS: Record<InventoryOpsIncidentTypeCode, string> = {
  RECEIVING_MISMATCH: "Receiving mismatch",
  STOCK_NEGATIVE_ATTEMPT: "Negative stock attempt",
  RESERVATION_CONFLICT: "Reservation conflict",
  STOCKTAKE_VARIANCE: "Stocktake variance",
  ADJUSTMENT_REVIEW: "Adjustment review",
  TRANSFER_EXCEPTION: "Transfer issue",
  BATCH_EXPIRY_EXCEPTION: "Batch or expiry issue",
  SERIAL_EXCEPTION: "Serial issue",
  DUPLICATE_OPERATION: "Duplicate operation",
  INVENTORY_DATA_INCONSISTENCY: "Data inconsistency",
  CONTROL_CONFIGURATION_EXCEPTION: "Control configuration issue",
};

export const INVENTORY_OPS_SEVERITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

export const INVENTORY_OPS_SEVERITY_LABELS: Record<
  (typeof INVENTORY_OPS_SEVERITIES)[keyof typeof INVENTORY_OPS_SEVERITIES],
  string
> = {
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
  CRITICAL: "Critical",
};

export const INVENTORY_OPS_INCIDENT_STATUSES = {
  OPEN: "OPEN",
  INVESTIGATING: "INVESTIGATING",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
  CLOSED: "CLOSED",
} as const;

export type InventoryOpsIncidentStatus =
  (typeof INVENTORY_OPS_INCIDENT_STATUSES)[keyof typeof INVENTORY_OPS_INCIDENT_STATUSES];

export const INVENTORY_OPS_INCIDENT_STATUS_LABELS: Record<InventoryOpsIncidentStatus, string> = {
  OPEN: "Open",
  INVESTIGATING: "Investigating",
  APPROVAL_PENDING: "Approval pending",
  RESOLVED: "Resolved",
  REJECTED: "Rejected",
  CLOSED: "Closed",
};

export const INVENTORY_OPS_RESOLUTION_ACTIONS = {
  CONFIRMED: "CONFIRMED",
  CORRECTED: "CORRECTED",
  REJECTED_AS_FALSE_POSITIVE: "REJECTED_AS_FALSE_POSITIVE",
  DUPLICATE_CLOSED: "DUPLICATE_CLOSED",
  DATA_CORRECTED: "DATA_CORRECTED",
  RECOUNT_REQUIRED: "RECOUNT_REQUIRED",
  MANUAL_REVIEW_COMPLETED: "MANUAL_REVIEW_COMPLETED",
} as const;

export const INVENTORY_OPS_RESOLUTION_ACTION_LABELS: Record<
  (typeof INVENTORY_OPS_RESOLUTION_ACTIONS)[keyof typeof INVENTORY_OPS_RESOLUTION_ACTIONS],
  string
> = {
  CONFIRMED: "Confirmed",
  CORRECTED: "Corrected",
  REJECTED_AS_FALSE_POSITIVE: "Rejected as false positive",
  DUPLICATE_CLOSED: "Closed as duplicate",
  DATA_CORRECTED: "Data corrected",
  RECOUNT_REQUIRED: "Recount required",
  MANUAL_REVIEW_COMPLETED: "Manual review completed",
};

export const INVENTORY_TRANSFER_STATUSES = {
  DRAFT: "DRAFT",
  REQUESTED: "REQUESTED",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  APPROVED: "APPROVED",
  DISPATCHED: "DISPATCHED",
  IN_TRANSIT: "IN_TRANSIT",
  RECEIVED: "RECEIVED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
  DISCREPANCY: "DISCREPANCY",
} as const;

export type InventoryTransferStatus =
  (typeof INVENTORY_TRANSFER_STATUSES)[keyof typeof INVENTORY_TRANSFER_STATUSES];

export const INVENTORY_TRANSFER_STATUS_LABELS: Record<InventoryTransferStatus, string> = {
  DRAFT: "Draft",
  REQUESTED: "Requested",
  APPROVAL_PENDING: "Approval pending",
  APPROVED: "Approved",
  DISPATCHED: "Dispatched",
  IN_TRANSIT: "In transit",
  RECEIVED: "Received",
  COMPLETED: "Completed",
  CANCELLED: "Cancelled",
  REJECTED: "Rejected",
  DISCREPANCY: "Discrepancy",
};

export type InventoryAuditAction =
  (typeof INVENTORY_AUDIT_ACTIONS)[keyof typeof INVENTORY_AUDIT_ACTIONS];
