/**
 * Purpose:
 * BP-009 IP-01 constants — statuses, catalogues, audit actions, permissions.
 * Operational labels only. Build Pack / IP identifiers stay out of the UI.
 *
 * Implementation Package:
 * BP-009 / IP-01 – Procurement Foundation & Supplier Relationship
 */

export const PROCUREMENT_STATUS_CODES = {
  ACTIVE: "ACTIVE",
  CONDITIONAL: "CONDITIONAL",
  SUSPENDED: "SUSPENDED",
  BLACKLISTED: "BLACKLISTED",
  INACTIVE: "INACTIVE",
} as const;

export type ProcurementStatusCode =
  (typeof PROCUREMENT_STATUS_CODES)[keyof typeof PROCUREMENT_STATUS_CODES];

export const PROCUREMENT_STATUS_LABELS: Record<ProcurementStatusCode, string> = {
  ACTIVE: "Active",
  CONDITIONAL: "Conditional",
  SUSPENDED: "Suspended",
  BLACKLISTED: "Blacklisted",
  INACTIVE: "Inactive",
};

export const QUALIFICATION_STATUS_CODES = {
  PENDING: "PENDING",
  QUALIFIED: "QUALIFIED",
  CONDITIONAL: "CONDITIONAL",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
} as const;

export type QualificationStatusCode =
  (typeof QUALIFICATION_STATUS_CODES)[keyof typeof QUALIFICATION_STATUS_CODES];

export const QUALIFICATION_STATUS_LABELS: Record<QualificationStatusCode, string> = {
  PENDING: "Pending",
  QUALIFIED: "Qualified",
  CONDITIONAL: "Conditional",
  FAILED: "Failed",
  EXPIRED: "Expired",
};

export const QUALIFICATION_TYPE_CODES = {
  GENERAL: "GENERAL",
  TECHNICAL: "TECHNICAL",
  COMPLIANCE: "COMPLIANCE",
  FINANCIAL: "FINANCIAL",
} as const;

export const PROCUREMENT_AUDIT_ACTIONS = {
  PROFILE_CREATED: "PROCUREMENT_PROFILE_CREATED",
  PROFILE_UPDATED: "PROCUREMENT_PROFILE_UPDATED",
  PARTY_LINKED: "PROCUREMENT_PARTY_LINKED",
  CATEGORY_ADDED: "PROCUREMENT_CATEGORY_ADDED",
  CATEGORY_REMOVED: "PROCUREMENT_CATEGORY_REMOVED",
  CAPABILITY_ADDED: "PROCUREMENT_CAPABILITY_ADDED",
  CAPABILITY_REMOVED: "PROCUREMENT_CAPABILITY_REMOVED",
  QUALIFICATION_CREATED: "PROCUREMENT_QUALIFICATION_CREATED",
  QUALIFICATION_UPDATED: "PROCUREMENT_QUALIFICATION_UPDATED",
  QUALIFICATION_APPROVED: "PROCUREMENT_QUALIFICATION_APPROVED",
  STATUS_CHANGED: "PROCUREMENT_STATUS_CHANGED",
  PREFERRED_CHANGED: "PROCUREMENT_PREFERRED_CHANGED",
  SUPPLIER_SUSPENDED: "PROCUREMENT_SUPPLIER_SUSPENDED",
  SUPPLIER_BLACKLISTED: "PROCUREMENT_SUPPLIER_BLACKLISTED",
  SUPPLIER_REACTIVATED: "PROCUREMENT_SUPPLIER_REACTIVATED",
  SUPPLIER_DEACTIVATED: "PROCUREMENT_SUPPLIER_DEACTIVATED",
  REQUEST_CREATED: "PROCUREMENT_REQUEST_CREATED",
  REQUEST_UPDATED: "PROCUREMENT_REQUEST_UPDATED",
  REQUEST_SUBMITTED: "PROCUREMENT_REQUEST_SUBMITTED",
  REQUEST_APPROVED: "PROCUREMENT_REQUEST_APPROVED",
  REQUEST_REJECTED: "PROCUREMENT_REQUEST_REJECTED",
  REQUEST_RETURNED: "PROCUREMENT_REQUEST_RETURNED",
  REQUEST_CANCELLED: "PROCUREMENT_REQUEST_CANCELLED",
  REQUEST_DOCUMENT_ATTACHED: "PROCUREMENT_REQUEST_DOCUMENT_ATTACHED",
  SOURCING_CREATED: "PROCUREMENT_SOURCING_CREATED",
  SOURCING_INVITED: "PROCUREMENT_SOURCING_INVITED",
  SOURCING_QUOTE_SUBMITTED: "PROCUREMENT_SOURCING_QUOTE_SUBMITTED",
  SOURCING_QUOTE_WITHDRAWN: "PROCUREMENT_SOURCING_QUOTE_WITHDRAWN",
  SOURCING_PORTAL_OPENED: "PROCUREMENT_SOURCING_PORTAL_OPENED",
  SOURCING_CLARIFICATION_ASKED: "PROCUREMENT_SOURCING_CLARIFICATION_ASKED",
  SOURCING_CLARIFICATION_ANSWERED: "PROCUREMENT_SOURCING_CLARIFICATION_ANSWERED",
  SOURCING_AWARDED: "PROCUREMENT_SOURCING_AWARDED",
  SOURCING_EXTENDED: "PROCUREMENT_SOURCING_EXTENDED",
  SOURCING_TENDER_CLOSED: "PROCUREMENT_SOURCING_TENDER_CLOSED",
  SOURCING_COMMITTEE_CONFIGURED: "PROCUREMENT_SOURCING_COMMITTEE_CONFIGURED",
  SOURCING_CRITERIA_CONFIGURED: "PROCUREMENT_SOURCING_CRITERIA_CONFIGURED",
  SOURCING_CRITERIA_LOCKED: "PROCUREMENT_SOURCING_CRITERIA_LOCKED",
  SOURCING_COMMITTEE_CONSTITUTED: "PROCUREMENT_SOURCING_COMMITTEE_CONSTITUTED",
  SOURCING_BID_CONTENT_VIEWED: "PROCUREMENT_SOURCING_BID_CONTENT_VIEWED",
  SOURCING_BID_OPENING_REQUESTED: "PROCUREMENT_SOURCING_BID_OPENING_REQUESTED",
  SOURCING_BID_OPENING_APPROVED: "PROCUREMENT_SOURCING_BID_OPENING_APPROVED",
  SOURCING_EVALUATION_STARTED: "PROCUREMENT_SOURCING_EVALUATION_STARTED",
  SOURCING_AWARD_SUBMITTED: "PROCUREMENT_SOURCING_AWARD_SUBMITTED",
  SOURCING_AWARD_APPROVED: "PROCUREMENT_SOURCING_AWARD_APPROVED",
  SOURCING_DUE_DILIGENCE_RECORDED: "PROCUREMENT_SOURCING_DUE_DILIGENCE_RECORDED",
  SOURCING_BIDS_OPENED: "PROCUREMENT_SOURCING_BIDS_OPENED",
  SOURCING_PHASE_SCORED: "PROCUREMENT_SOURCING_PHASE_SCORED",
  PO_CREATED: "PROCUREMENT_PO_CREATED",
  PO_SUBMITTED: "PROCUREMENT_PO_SUBMITTED",
  PO_APPROVED: "PROCUREMENT_PO_APPROVED",
  PO_APPROVAL_REJECTED: "PROCUREMENT_PO_APPROVAL_REJECTED",
  PO_ISSUED: "PROCUREMENT_PO_ISSUED",
  PO_ACCEPTED: "PROCUREMENT_PO_ACCEPTED",
  PO_REJECTED_BY_SUPPLIER: "PROCUREMENT_PO_REJECTED_BY_SUPPLIER",
  PO_CHANGE_REQUESTED: "PROCUREMENT_PO_CHANGE_REQUESTED",
  PO_AMENDED: "PROCUREMENT_PO_AMENDED",
  PO_CANCELLED: "PROCUREMENT_PO_CANCELLED",
  PO_CLOSED: "PROCUREMENT_PO_CLOSED",
  CONTRACT_CREATED: "PROCUREMENT_CONTRACT_CREATED",
  CONTRACT_SUBMITTED: "PROCUREMENT_CONTRACT_SUBMITTED",
  CONTRACT_APPROVED: "PROCUREMENT_CONTRACT_APPROVED",
  CONTRACT_REJECTED: "PROCUREMENT_CONTRACT_REJECTED",
  CONTRACT_PENDING_EXECUTION: "PROCUREMENT_CONTRACT_PENDING_EXECUTION",
  CONTRACT_ACTIVATED: "PROCUREMENT_CONTRACT_ACTIVATED",
  CONTRACT_AMENDED: "PROCUREMENT_CONTRACT_AMENDED",
  CONTRACT_RENEWED: "PROCUREMENT_CONTRACT_RENEWED",
  CONTRACT_SUSPENDED: "PROCUREMENT_CONTRACT_SUSPENDED",
  CONTRACT_TERMINATED: "PROCUREMENT_CONTRACT_TERMINATED",
  CONTRACT_EXPIRED: "PROCUREMENT_CONTRACT_EXPIRED",
  CONTRACT_CLOSED: "PROCUREMENT_CONTRACT_CLOSED",
  CONTRACT_CALLOFF_CREATED: "PROCUREMENT_CONTRACT_CALLOFF_CREATED",
  RECEIPT_CREATED: "PROCUREMENT_RECEIPT_CREATED",
  RECEIPT_SUBMITTED: "PROCUREMENT_RECEIPT_SUBMITTED",
  RECEIPT_CONFIRMED: "PROCUREMENT_RECEIPT_CONFIRMED",
  RECEIPT_REJECTED: "PROCUREMENT_RECEIPT_REJECTED",
  RECEIPT_AMENDED: "PROCUREMENT_RECEIPT_AMENDED",
  INSPECTION_RECORDED: "PROCUREMENT_INSPECTION_RECORDED",
  GOODS_HANDOFF_CREATED: "PROCUREMENT_GOODS_HANDOFF_CREATED",
  GOODS_HANDOFF_SUCCEEDED: "PROCUREMENT_GOODS_HANDOFF_SUCCEEDED",
  GOODS_HANDOFF_FAILED: "PROCUREMENT_GOODS_HANDOFF_FAILED",
  ASSET_HANDOFF_CREATED: "PROCUREMENT_ASSET_HANDOFF_CREATED",
  SERVICE_CONFIRMED: "PROCUREMENT_SERVICE_CONFIRMED",
  DISCREPANCY_RECORDED: "PROCUREMENT_DISCREPANCY_RECORDED",
  OVER_DELIVERY_FLAGGED: "PROCUREMENT_OVER_DELIVERY_FLAGGED",
  INVOICE_CREATED: "PROCUREMENT_INVOICE_CREATED",
  INVOICE_CAPTURED: "PROCUREMENT_INVOICE_CAPTURED",
  INVOICE_MATCHED: "PROCUREMENT_INVOICE_MATCHED",
  INVOICE_VARIANCE: "PROCUREMENT_INVOICE_VARIANCE",
  INVOICE_UNMATCHED: "PROCUREMENT_INVOICE_UNMATCHED",
  INVOICE_DUPLICATE_DETECTED: "PROCUREMENT_INVOICE_DUPLICATE_DETECTED",
  INVOICE_APPROVED: "PROCUREMENT_INVOICE_APPROVED",
  INVOICE_REJECTED: "PROCUREMENT_INVOICE_REJECTED",
  AP_HANDOFF_CREATED: "PROCUREMENT_AP_HANDOFF_CREATED",
  AP_HANDOFF_SUCCEEDED: "PROCUREMENT_AP_HANDOFF_SUCCEEDED",
  AP_HANDOFF_FAILED: "PROCUREMENT_AP_HANDOFF_FAILED",
  EXCEPTION_RAISED: "PROCUREMENT_EXCEPTION_RAISED",
  EXCEPTION_ASSIGNED: "PROCUREMENT_EXCEPTION_ASSIGNED",
  EXCEPTION_RESOLVED: "PROCUREMENT_EXCEPTION_RESOLVED",
  EXCEPTION_APPROVED: "PROCUREMENT_EXCEPTION_APPROVED",
  EXCEPTION_CLOSED: "PROCUREMENT_EXCEPTION_CLOSED",
  EXCEPTION_CANCELLED: "PROCUREMENT_EXCEPTION_CANCELLED",
  PERFORMANCE_EVENT_RECORDED: "PROCUREMENT_PERFORMANCE_EVENT_RECORDED",
  SCORECARD_COMPUTED: "PROCUREMENT_SCORECARD_COMPUTED",
  GOVERNANCE_PROPOSED: "PROCUREMENT_GOVERNANCE_PROPOSED",
  GOVERNANCE_APPROVED: "PROCUREMENT_GOVERNANCE_APPROVED",
  GOVERNANCE_REJECTED: "PROCUREMENT_GOVERNANCE_REJECTED",
  PREFERRED_GRANTED: "PROCUREMENT_PREFERRED_GRANTED",
  PREFERRED_REVOKED: "PROCUREMENT_PREFERRED_REVOKED",
  EVALUATION_SUBMITTED: "PROCUREMENT_EVALUATION_SUBMITTED",
  PERFORMANCE_CONTROL_UPDATED: "PROCUREMENT_PERFORMANCE_CONTROL_UPDATED",
} as const;

export const PROCUREMENT_PERMISSIONS = {
  VIEW: "Procurement.Supplier.Read",
  CREATE: "Procurement.Supplier.Create",
  UPDATE: "Procurement.Supplier.Update",
  QUALIFY: "Procurement.Qualification.Manage",
  STATUS: "Procurement.Status.Manage",
  PREFERRED: "Procurement.Preferred.Manage",
  BLACKLIST: "Procurement.Blacklist.Manage",
  REQUEST_READ: "Procurement.Request.Read",
  REQUEST_CREATE: "Procurement.Request.Create",
  REQUEST_UPDATE: "Procurement.Request.Update",
  REQUEST_SUBMIT: "Procurement.Request.Execute",
  REQUEST_APPROVE: "Procurement.Request.Approve",
  REQUEST_CANCEL: "Procurement.Request.Deactivate",
  SOURCING_READ: "Procurement.Sourcing.Read",
  SOURCING_CREATE: "Procurement.Sourcing.Create",
  SOURCING_UPDATE: "Procurement.Sourcing.Update",
  SOURCING_AWARD: "Procurement.Sourcing.Approve",
  PO_READ: "Procurement.PurchaseOrder.Read",
  PO_CREATE: "Procurement.PurchaseOrder.Create",
  PO_UPDATE: "Procurement.PurchaseOrder.Update",
  PO_SUBMIT: "Procurement.PurchaseOrder.Execute",
  PO_APPROVE: "Procurement.PurchaseOrder.Approve",
  PO_ISSUE: "Procurement.PurchaseOrder.Issue",
  PO_AMEND: "Procurement.PurchaseOrder.Amend",
  PO_CANCEL: "Procurement.PurchaseOrder.Deactivate",
  PO_CLOSE: "Procurement.PurchaseOrder.Close",
  CONTRACT_READ: "Procurement.Contract.Read",
  CONTRACT_CREATE: "Procurement.Contract.Create",
  CONTRACT_UPDATE: "Procurement.Contract.Update",
  CONTRACT_SUBMIT: "Procurement.Contract.Execute",
  CONTRACT_APPROVE: "Procurement.Contract.Approve",
  CONTRACT_ACTIVATE: "Procurement.Contract.Activate",
  CONTRACT_AMEND: "Procurement.Contract.Amend",
  CONTRACT_CALLOFF: "Procurement.Contract.CallOff",
  CONTRACT_SUSPEND: "Procurement.Contract.Deactivate",
  CONTRACT_CLOSE: "Procurement.Contract.Close",
  RECEIVING_READ: "Procurement.Receiving.Read",
  RECEIVING_CREATE: "Procurement.Receiving.Create",
  RECEIVING_CONFIRM: "Procurement.Receiving.Confirm",
  RECEIVING_REJECT: "Procurement.Receiving.Reject",
  RECEIVING_INSPECTION: "Procurement.Receiving.Inspect",
  RECEIVING_DISCREPANCY: "Procurement.Receiving.Discrepancy",
  INVOICE_READ: "Procurement.Invoice.Read",
  INVOICE_CREATE: "Procurement.Invoice.Create",
  INVOICE_UPDATE: "Procurement.Invoice.Update",
  INVOICE_CAPTURE: "Procurement.Invoice.Execute",
  INVOICE_MATCH: "Procurement.Invoice.Match",
  INVOICE_APPROVE: "Procurement.Invoice.Approve",
  INVOICE_REJECT: "Procurement.Invoice.Reject",
  EXCEPTION_READ: "Procurement.Exception.Read",
  EXCEPTION_CREATE: "Procurement.Exception.Create",
  EXCEPTION_ASSIGN: "Procurement.Exception.Assign",
  EXCEPTION_RESOLVE: "Procurement.Exception.Resolve",
  EXCEPTION_APPROVE: "Procurement.Exception.Approve",
  EXCEPTION_CLOSE: "Procurement.Exception.Close",
  EXCEPTION_CANCEL: "Procurement.Exception.Deactivate",
  PERFORMANCE_READ: "Procurement.Performance.Read",
  PERFORMANCE_MANAGE: "Procurement.Performance.Manage",
  GOVERNANCE_PROPOSE: "Procurement.Governance.Propose",
  GOVERNANCE_APPROVE: "Procurement.Governance.Approve",
  ANALYTICS_READ: "Procurement.Analytics.Read",
} as const;

export type ProcurementPermission =
  (typeof PROCUREMENT_PERMISSIONS)[keyof typeof PROCUREMENT_PERMISSIONS];

export const ALL_PROCUREMENT_PERMISSIONS = Object.values(PROCUREMENT_PERMISSIONS);

export const STATUS_CODES_REQUIRING_REASON: ProcurementStatusCode[] = [
  PROCUREMENT_STATUS_CODES.SUSPENDED,
  PROCUREMENT_STATUS_CODES.BLACKLISTED,
  PROCUREMENT_STATUS_CODES.INACTIVE,
];

export const PARTICIPATING_STATUS_CODES: ProcurementStatusCode[] = [
  PROCUREMENT_STATUS_CODES.ACTIVE,
  PROCUREMENT_STATUS_CODES.CONDITIONAL,
];

export const VALID_QUALIFICATION_OUTCOMES: QualificationStatusCode[] = [
  QUALIFICATION_STATUS_CODES.QUALIFIED,
  QUALIFICATION_STATUS_CODES.CONDITIONAL,
];

export const PURCHASE_REQUEST_STATUSES = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  IN_APPROVAL: "IN_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  RETURNED: "RETURNED",
  CANCELLED: "CANCELLED",
} as const;

export type PurchaseRequestStatus =
  (typeof PURCHASE_REQUEST_STATUSES)[keyof typeof PURCHASE_REQUEST_STATUSES];

export const PURCHASE_REQUEST_STATUS_LABELS: Record<PurchaseRequestStatus, string> = {
  DRAFT: "Draft",
  SUBMITTED: "Submitted",
  IN_APPROVAL: "Pending approval",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  RETURNED: "Returned",
  CANCELLED: "Cancelled",
};

export const PURCHASE_REQUEST_ORIGIN_TYPES = {
  AD_HOC: "AD_HOC",
  INVENTORY_REORDER: "INVENTORY_REORDER",
  BUSINESS_REQUIREMENT: "BUSINESS_REQUIREMENT",
  CONTRACT_REFERENCE: "CONTRACT_REFERENCE",
  RECURRING: "RECURRING",
  PROJECT_REFERENCE: "PROJECT_REFERENCE",
  PROCUREMENT_DEMAND: "PROCUREMENT_DEMAND",
} as const;

export type PurchaseRequestOriginType =
  (typeof PURCHASE_REQUEST_ORIGIN_TYPES)[keyof typeof PURCHASE_REQUEST_ORIGIN_TYPES];

export const PURCHASE_REQUEST_ORIGIN_LABELS: Record<PurchaseRequestOriginType, string> = {
  AD_HOC: "Ad-hoc",
  INVENTORY_REORDER: "Inventory",
  BUSINESS_REQUIREMENT: "Business requirement",
  CONTRACT_REFERENCE: "Contract",
  RECURRING: "Recurring",
  PROJECT_REFERENCE: "Project",
  PROCUREMENT_DEMAND: "Plan",
};

export const PROCUREMENT_TYPES = {
  GOODS: "GOODS",
  SERVICES: "SERVICES",
  ASSETS: "ASSETS",
  MIXED: "MIXED",
} as const;

export type ProcurementTypeCode = (typeof PROCUREMENT_TYPES)[keyof typeof PROCUREMENT_TYPES];

export const PROCUREMENT_TYPE_LABELS: Record<ProcurementTypeCode, string> = {
  GOODS: "Goods",
  SERVICES: "Services",
  ASSETS: "Assets",
  MIXED: "Mixed",
};

export const BUDGET_SOURCES = {
  PLANNED: "PLANNED",
  EXISTING_BUDGET: "EXISTING_BUDGET",
  AD_HOC_BUDGET_APPROVAL: "AD_HOC_BUDGET_APPROVAL",
} as const;

export type BudgetSourceCode = (typeof BUDGET_SOURCES)[keyof typeof BUDGET_SOURCES];

export const BUDGET_SOURCE_LABELS: Record<BudgetSourceCode, string> = {
  PLANNED: "Planned procurement",
  EXISTING_BUDGET: "Existing budget",
  AD_HOC_BUDGET_APPROVAL: "Ad-hoc budget approval",
};

export const BUDGET_CHECK_STATUSES = {
  WITHIN_BUDGET: "WITHIN_BUDGET",
  OVER_BUDGET: "OVER_BUDGET",
  EVIDENCE_RECORDED: "EVIDENCE_RECORDED",
  NOT_APPLICABLE: "NOT_APPLICABLE",
} as const;

export type BudgetCheckStatus =
  (typeof BUDGET_CHECK_STATUSES)[keyof typeof BUDGET_CHECK_STATUSES];

export const BUDGET_CHECK_STATUS_LABELS: Record<BudgetCheckStatus, string> = {
  WITHIN_BUDGET: "Within budget",
  OVER_BUDGET: "Above budget",
  EVIDENCE_RECORDED: "Budget approval recorded",
  NOT_APPLICABLE: "No available-budget snapshot",
};

export const OVER_BUDGET_MODES = {
  BLOCK: "BLOCK",
  REQUIRE_EVIDENCE: "REQUIRE_EVIDENCE",
} as const;

export type OverBudgetMode = (typeof OVER_BUDGET_MODES)[keyof typeof OVER_BUDGET_MODES];

export const EDITABLE_REQUEST_STATUSES: PurchaseRequestStatus[] = [
  PURCHASE_REQUEST_STATUSES.DRAFT,
  PURCHASE_REQUEST_STATUSES.RETURNED,
];

export const PENDING_APPROVAL_STATUSES: PurchaseRequestStatus[] = [
  PURCHASE_REQUEST_STATUSES.SUBMITTED,
  PURCHASE_REQUEST_STATUSES.IN_APPROVAL,
];

export const SOURCING_EVENT_STATUSES = {
  ISSUED: "ISSUED",
  CLOSED: "CLOSED",
  EVALUATING: "EVALUATING",
  AWARDED: "AWARDED",
} as const;

export type SourcingEventStatus =
  (typeof SOURCING_EVENT_STATUSES)[keyof typeof SOURCING_EVENT_STATUSES];

export const SOURCING_EVENT_STATUS_LABELS: Record<SourcingEventStatus, string> = {
  ISSUED: "Open",
  CLOSED: "Closed",
  EVALUATING: "Evaluating",
  AWARDED: "Awarded",
};

export const PO_SOURCE_TYPES = {
  AWARD: "AWARD",
  PURCHASE_REQUEST: "PURCHASE_REQUEST",
  CONTRACT_CALLOFF: "CONTRACT_CALLOFF",
  DIRECT: "DIRECT",
} as const;

export type PoSourceType = (typeof PO_SOURCE_TYPES)[keyof typeof PO_SOURCE_TYPES];

export const PO_STATUSES = {
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  ISSUED: "ISSUED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  CHANGE_REQUESTED: "CHANGE_REQUESTED",
  CANCELLED: "CANCELLED",
  PARTIALLY_FULFILLED: "PARTIALLY_FULFILLED",
  FULFILLED: "FULFILLED",
  CLOSED: "CLOSED",
} as const;

export type PoStatus = (typeof PO_STATUSES)[keyof typeof PO_STATUSES];

export const PO_STATUS_LABELS: Record<PoStatus, string> = {
  DRAFT: "Draft",
  PENDING_APPROVAL: "Pending approval",
  APPROVED: "Approved",
  ISSUED: "Issued",
  ACCEPTED: "Accepted",
  REJECTED: "Rejected",
  CHANGE_REQUESTED: "Change requested",
  CANCELLED: "Cancelled",
  PARTIALLY_FULFILLED: "Partially fulfilled",
  FULFILLED: "Fulfilled",
  CLOSED: "Closed",
};

export const PO_VERSION_STATUSES = {
  DRAFT: "DRAFT",
  ISSUED: "ISSUED",
  SUPERSEDED: "SUPERSEDED",
  ACCEPTED: "ACCEPTED",
} as const;

export const PO_SUPPLIER_ACTIONS = {
  ACCEPT: "ACCEPT",
  REJECT: "REJECT",
  REQUEST_CHANGE: "REQUEST_CHANGE",
} as const;

export const CONTRACT_STATUSES = {
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  PENDING_EXECUTION: "PENDING_EXECUTION",
  ACTIVE: "ACTIVE",
  EXPIRING: "EXPIRING",
  EXPIRED: "EXPIRED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
  TERMINATED: "TERMINATED",
} as const;

export type ContractStatus = (typeof CONTRACT_STATUSES)[keyof typeof CONTRACT_STATUSES];

export const CONTRACT_STATUS_LABELS: Record<ContractStatus, string> = {
  DRAFT: "Draft",
  PENDING_APPROVAL: "Pending approval",
  APPROVED: "Approved",
  PENDING_EXECUTION: "Pending execution",
  ACTIVE: "Active",
  EXPIRING: "Expiring soon",
  EXPIRED: "Expired",
  CLOSED: "Closed",
  CANCELLED: "Cancelled",
  REJECTED: "Rejected",
  SUSPENDED: "Suspended",
  TERMINATED: "Terminated",
};

export const CONTRACT_SOURCE_TYPES = {
  AWARD: "AWARD",
  PURCHASE_REQUEST: "PURCHASE_REQUEST",
  MANUAL: "MANUAL",
} as const;

export type ContractSourceType =
  (typeof CONTRACT_SOURCE_TYPES)[keyof typeof CONTRACT_SOURCE_TYPES];

export const CONTRACT_VALUE_TYPES = {
  FIXED: "FIXED",
  CAPPED: "CAPPED",
  INFORMATIONAL: "INFORMATIONAL",
} as const;

export type ContractValueType =
  (typeof CONTRACT_VALUE_TYPES)[keyof typeof CONTRACT_VALUE_TYPES];

export const CONTRACT_VERSION_STATUSES = {
  DRAFT: "DRAFT",
  CURRENT: "CURRENT",
  SUPERSEDED: "SUPERSEDED",
} as const;

export const PO_LINE_TYPES = {
  INVENTORY: "INVENTORY",
  ASSET: "ASSET",
  SERVICE: "SERVICE",
} as const;

export type PoLineType = (typeof PO_LINE_TYPES)[keyof typeof PO_LINE_TYPES];

export const RECEIPT_TYPES = {
  GOODS_RECEIPT: "GOODS_RECEIPT",
  ASSET_RECEIPT: "ASSET_RECEIPT",
  SERVICE_CONFIRMATION: "SERVICE_CONFIRMATION",
} as const;

export type ReceiptType = (typeof RECEIPT_TYPES)[keyof typeof RECEIPT_TYPES];

export const RECEIPT_STATUSES = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  CONFIRMED: "CONFIRMED",
  REJECTED: "REJECTED",
} as const;

export type ReceiptStatus = (typeof RECEIPT_STATUSES)[keyof typeof RECEIPT_STATUSES];

export const RECEIPT_HANDOFF_STATUSES = {
  PENDING: "PENDING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
} as const;

export const RECEIPT_HANDOFF_TYPES = {
  INVENTORY: "INVENTORY",
  ASSET: "ASSET",
} as const;

export const INSPECTION_STATUSES = {
  NOT_REQUIRED: "NOT_REQUIRED",
  PENDING: "PENDING",
  PASSED: "PASSED",
  FAILED: "FAILED",
} as const;

export const OVER_RECEIPT_POLICIES = {
  BLOCK: "BLOCK",
  ALLOW_EXCEPTION: "ALLOW_EXCEPTION",
} as const;

export const DISCREPANCY_TYPES = {
  SHORT_DELIVERY: "SHORT_DELIVERY",
  OVER_DELIVERY: "OVER_DELIVERY",
  DAMAGED: "DAMAGED",
  WRONG_ITEM: "WRONG_ITEM",
  WRONG_QUANTITY: "WRONG_QUANTITY",
  OTHER: "OTHER",
} as const;

export const LINE_FULFILMENT_STATUSES = {
  NOT_RECEIVED: "NOT_RECEIVED",
  PARTIALLY_FULFILLED: "PARTIALLY_FULFILLED",
  FULFILLED: "FULFILLED",
  OVERDUE: "OVERDUE",
} as const;

export const PO_FULFILMENT_STATUSES = {
  NOT_FULFILLED: "NOT_FULFILLED",
  PARTIALLY_FULFILLED: "PARTIALLY_FULFILLED",
  FULFILLED: "FULFILLED",
} as const;

export const INVOICE_STATUSES = {
  DRAFT: "DRAFT",
  CAPTURED: "CAPTURED",
  MATCHED: "MATCHED",
  VARIANCE: "VARIANCE",
  UNMATCHED: "UNMATCHED",
  DUPLICATE: "DUPLICATE",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  PAYMENT_READY: "PAYMENT_READY",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
} as const;

export type InvoiceStatus = (typeof INVOICE_STATUSES)[keyof typeof INVOICE_STATUSES];

export const INVOICE_STATUS_LABELS: Record<InvoiceStatus, string> = {
  DRAFT: "Draft",
  CAPTURED: "Captured",
  MATCHED: "Matched",
  VARIANCE: "Variance",
  UNMATCHED: "Unmatched",
  DUPLICATE: "Duplicate",
  PENDING_APPROVAL: "Pending approval",
  APPROVED: "Approved",
  PAYMENT_READY: "Payment ready",
  REJECTED: "Rejected",
  CANCELLED: "Cancelled",
};

export const MATCHING_MODES = {
  TWO_WAY: "TWO_WAY",
  THREE_WAY: "THREE_WAY",
  FOUR_WAY: "FOUR_WAY",
} as const;

export type MatchingMode = (typeof MATCHING_MODES)[keyof typeof MATCHING_MODES];

export const MATCH_OUTCOMES = {
  PENDING: "PENDING",
  MATCHED: "MATCHED",
  VARIANCE: "VARIANCE",
  UNMATCHED: "UNMATCHED",
  DUPLICATE: "DUPLICATE",
} as const;

export type MatchOutcome = (typeof MATCH_OUTCOMES)[keyof typeof MATCH_OUTCOMES];

export const MATCH_VARIANCE_TYPES = {
  PRICE: "PRICE",
  QUANTITY: "QUANTITY",
  TAX: "TAX",
  RECEIPT_MISSING: "RECEIPT_MISSING",
  INSPECTION_PENDING: "INSPECTION_PENDING",
  INSPECTION_FAILED: "INSPECTION_FAILED",
  PO_COVERAGE: "PO_COVERAGE",
  PO_LINE_MISSING: "PO_LINE_MISSING",
} as const;

export const DUPLICATE_POLICIES = {
  BLOCK: "BLOCK",
  EXCEPTION: "EXCEPTION",
} as const;

export const AP_HANDOFF_STATUSES = {
  PENDING: "PENDING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
} as const;

export const EXCEPTION_STATUSES = {
  OPEN: "OPEN",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED_PENDING_APPROVAL: "RESOLVED_PENDING_APPROVAL",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
} as const;

export type ExceptionStatus = (typeof EXCEPTION_STATUSES)[keyof typeof EXCEPTION_STATUSES];

export const EXCEPTION_STATUS_LABELS: Record<ExceptionStatus, string> = {
  OPEN: "Open",
  ASSIGNED: "Assigned",
  IN_PROGRESS: "In progress",
  RESOLVED_PENDING_APPROVAL: "Pending approval",
  CLOSED: "Closed",
  CANCELLED: "Cancelled",
};

export const EXCEPTION_SEVERITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

export type ExceptionSeverity = (typeof EXCEPTION_SEVERITIES)[keyof typeof EXCEPTION_SEVERITIES];

export const EXCEPTION_RAISED_FROM = {
  SYSTEM_MATCH: "SYSTEM_MATCH",
  SYSTEM_RECEIPT: "SYSTEM_RECEIPT",
  USER: "USER",
} as const;

export const EXCEPTION_OBJECT_TYPES = {
  PURCHASE_REQUEST: "PURCHASE_REQUEST",
  SOURCING_EVENT: "SOURCING_EVENT",
  PURCHASE_ORDER: "PURCHASE_ORDER",
  CONTRACT: "CONTRACT",
  RECEIPT: "RECEIPT",
  INVOICE: "INVOICE",
  MATCH: "MATCH",
  PROFILE: "PROFILE",
} as const;

export const EXCEPTION_TYPE_CODES = {
  PRICE_VARIANCE: "PRICE_VARIANCE",
  QUANTITY_VARIANCE: "QUANTITY_VARIANCE",
  PARTIAL_DELIVERY: "PARTIAL_DELIVERY",
  OVER_DELIVERY: "OVER_DELIVERY",
  UNDER_DELIVERY: "UNDER_DELIVERY",
  DAMAGED_GOODS: "DAMAGED_GOODS",
  REJECTED_GOODS: "REJECTED_GOODS",
  MISSING_RECEIPT: "MISSING_RECEIPT",
  INVOICE_MISMATCH: "INVOICE_MISMATCH",
  DUPLICATE_INVOICE: "DUPLICATE_INVOICE",
  EXPIRED_CONTRACT: "EXPIRED_CONTRACT",
  PO_EXPIRY: "PO_EXPIRY",
  SUPPLIER_DISPUTE: "SUPPLIER_DISPUTE",
  LATE_DELIVERY: "LATE_DELIVERY",
  QUALITY_FAILURE: "QUALITY_FAILURE",
} as const;

export const EXCEPTION_ACTION_TYPES = {
  RAISED: "RAISED",
  ASSIGNED: "ASSIGNED",
  STARTED: "STARTED",
  RESOLUTION_RECORDED: "RESOLUTION_RECORDED",
  APPROVED: "APPROVED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
  COMMENT: "COMMENT",
} as const;

export const HIGH_EXCEPTION_SEVERITIES = [
  EXCEPTION_SEVERITIES.HIGH,
  EXCEPTION_SEVERITIES.CRITICAL,
] as const;

export const PERFORMANCE_MEASURE_CODES = {
  DELIVERY_ON_TIME: "DELIVERY_ON_TIME",
  DELIVERY_LATE: "DELIVERY_LATE",
  FULFILMENT_PARTIAL: "FULFILMENT_PARTIAL",
  FULFILMENT_OVER: "FULFILMENT_OVER",
  QUALITY_REJECTION: "QUALITY_REJECTION",
  INVOICE_VARIANCE: "INVOICE_VARIANCE",
  INVOICE_DUPLICATE: "INVOICE_DUPLICATE",
  DISPUTE_OPENED: "DISPUTE_OPENED",
  DISPUTE_RESOLVED: "DISPUTE_RESOLVED",
  PO_ISSUED: "PO_ISSUED",
} as const;

export const PERFORMANCE_SOURCE_TYPES = {
  PURCHASE_ORDER: "PURCHASE_ORDER",
  RECEIPT: "RECEIPT",
  INVOICE: "INVOICE",
  EXCEPTION: "EXCEPTION",
  CONTRACT: "CONTRACT",
} as const;

export const GOVERNANCE_PROPOSAL_TYPES = {
  GRANT_PREFERRED: "GRANT_PREFERRED",
  REVOKE_PREFERRED: "REVOKE_PREFERRED",
  SUSPEND: "SUSPEND",
  BLACKLIST: "BLACKLIST",
  REACTIVATE: "REACTIVATE",
} as const;

export const GOVERNANCE_PROPOSAL_STATUSES = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
} as const;

export const SCORECARD_STATUSES = {
  PUBLISHED: "PUBLISHED",
} as const;

export const PERFORMANCE_EVALUATOR_TYPES = {
  INTERNAL: "INTERNAL",
  SUPPLIER: "SUPPLIER",
} as const;

export const PERFORMANCE_EVALUATION_STATUSES = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
} as const;

export const LIFECYCLE_ANCHOR_TYPES = {
  PURCHASE_REQUEST: "PURCHASE_REQUEST",
  SOURCING_EVENT: "SOURCING_EVENT",
  PURCHASE_ORDER: "PURCHASE_ORDER",
  CONTRACT: "CONTRACT",
  RECEIPT: "RECEIPT",
  INVOICE: "INVOICE",
} as const;

export const PROCUREMENT_SAVINGS_FORMULA =
  "Savings = estimated purchase request value minus awarded amount (same currency).";
