/**
 * Purpose:
 * Typed, fail-closed errors for procurement foundation operations.
 * Messages use operational language — no Build Pack or engine jargon.
 *
 * Implementation Package:
 * BP-009 / IP-01 – Procurement Foundation & Supplier Relationship
 */

export const PROCUREMENT_ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  SESSION_REQUIRED: "SESSION_REQUIRED",
  BUSINESS_CONTEXT_REQUIRED: "BUSINESS_CONTEXT_REQUIRED",
  CROSS_BUSINESS_ACCESS: "CROSS_BUSINESS_ACCESS",
  UNAUTHORIZED: "UNAUTHORIZED",
  PARTY_NOT_FOUND: "PARTY_NOT_FOUND",
  PARTY_NOT_SUPPLIER: "PARTY_NOT_SUPPLIER",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  DUPLICATE_PROFILE: "DUPLICATE_PROFILE",
  QUALIFICATION_NOT_FOUND: "QUALIFICATION_NOT_FOUND",
  QUALIFICATION_EXPIRED: "QUALIFICATION_EXPIRED",
  SUPPLIER_SUSPENDED: "SUPPLIER_SUSPENDED",
  SUPPLIER_BLACKLISTED: "SUPPLIER_BLACKLISTED",
  SUPPLIER_NOT_ELIGIBLE: "SUPPLIER_NOT_ELIGIBLE",
  INVALID_CATEGORY: "INVALID_CATEGORY",
  INVALID_CAPABILITY: "INVALID_CAPABILITY",
  INVALID_STATUS: "INVALID_STATUS",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  STATUS_REASON_REQUIRED: "STATUS_REASON_REQUIRED",
  INVALID_QUALIFICATION_OUTCOME: "INVALID_QUALIFICATION_OUTCOME",
  INVALID_QUALIFICATION_TYPE: "INVALID_QUALIFICATION_TYPE",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  NUMBERING_POLICY_MISSING: "NUMBERING_POLICY_MISSING",
  CONCURRENT_UPDATE: "CONCURRENT_UPDATE",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  EMPTY_REQUEST: "EMPTY_REQUEST",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  INVALID_ESTIMATED_VALUE: "INVALID_ESTIMATED_VALUE",
  CURRENCY_REQUIRED: "CURRENCY_REQUIRED",
  BUDGET_SOURCE_REQUIRED: "BUDGET_SOURCE_REQUIRED",
  BUDGET_REFERENCE_REQUIRED: "BUDGET_REFERENCE_REQUIRED",
  OVER_BUDGET: "OVER_BUDGET",
  BUDGET_EVIDENCE_REQUIRED: "BUDGET_EVIDENCE_REQUIRED",
  SELF_APPROVAL: "SELF_APPROVAL",
  REQUEST_NOT_EDITABLE: "REQUEST_NOT_EDITABLE",
  INVALID_ORIGIN: "INVALID_ORIGIN",
  DECISION_REASON_REQUIRED: "DECISION_REASON_REQUIRED",
  SOURCING_NOT_FOUND: "SOURCING_NOT_FOUND",
  REQUEST_NOT_APPROVED: "REQUEST_NOT_APPROVED",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  AWARD_INVALID: "AWARD_INVALID",
  TENDER_CLOSED: "TENDER_CLOSED",
  EXTENSION_INVALID: "EXTENSION_INVALID",
  INVITATION_REVOKED: "INVITATION_REVOKED",
  EVALUATION_STAGE_INVALID: "EVALUATION_STAGE_INVALID",
  DUE_DILIGENCE_INCOMPLETE: "DUE_DILIGENCE_INCOMPLETE",
  BIDS_NOT_OPENED: "BIDS_NOT_OPENED",
  CRITERIA_NOT_LOCKED: "CRITERIA_NOT_LOCKED",
  CRITERIA_LOCKED: "CRITERIA_LOCKED",
  AWARD_NOT_APPROVED: "AWARD_NOT_APPROVED",
  AWARD_OVERRIDE_REQUIRED: "AWARD_OVERRIDE_REQUIRED",
  AWARD_LINES_REQUIRED: "AWARD_LINES_REQUIRED",
  PO_NOT_FOUND: "PO_NOT_FOUND",
  PO_ALREADY_EXISTS: "PO_ALREADY_EXISTS",
  SKIP_RFX_NOT_ALLOWED: "SKIP_RFX_NOT_ALLOWED",
  PO_NOT_EDITABLE: "PO_NOT_EDITABLE",
  PO_VERSION_INVALID: "PO_VERSION_INVALID",
  PO_TOKEN_INVALID: "PO_TOKEN_INVALID",
  PO_TOKEN_REVOKED: "PO_TOKEN_REVOKED",
  PO_REASON_REQUIRED: "PO_REASON_REQUIRED",
  CONTRACT_NOT_FOUND: "CONTRACT_NOT_FOUND",
  CONTRACT_NOT_EDITABLE: "CONTRACT_NOT_EDITABLE",
  CONTRACT_INVALID_STATE: "CONTRACT_INVALID_STATE",
  CONTRACT_CALLOFF_NOT_ALLOWED: "CONTRACT_CALLOFF_NOT_ALLOWED",
  CONTRACT_CEILING_EXCEEDED: "CONTRACT_CEILING_EXCEEDED",
  CONTRACT_ALREADY_EXISTS: "CONTRACT_ALREADY_EXISTS",
  DIRECT_CONTRACT_NOT_ALLOWED: "DIRECT_CONTRACT_NOT_ALLOWED",
  CONTRACT_EXECUTION_EVIDENCE_REQUIRED: "CONTRACT_EXECUTION_EVIDENCE_REQUIRED",
  RECEIPT_NOT_FOUND: "RECEIPT_NOT_FOUND",
  RECEIPT_NOT_EDITABLE: "RECEIPT_NOT_EDITABLE",
  PO_NOT_RECEIVABLE: "PO_NOT_RECEIVABLE",
  OVER_RECEIPT_BLOCKED: "OVER_RECEIPT_BLOCKED",
  INVALID_RECEIPT_QUANTITY: "INVALID_RECEIPT_QUANTITY",
  PO_LINE_NOT_FOUND: "PO_LINE_NOT_FOUND",
  HANDOFF_FAILED: "HANDOFF_FAILED",
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVOICE_NOT_EDITABLE: "INVOICE_NOT_EDITABLE",
  INVOICE_DUPLICATE: "INVOICE_DUPLICATE",
  INVOICE_PO_REQUIRED: "INVOICE_PO_REQUIRED",
  INVOICE_NOT_MATCHED: "INVOICE_NOT_MATCHED",
  INVOICE_NOT_APPROVABLE: "INVOICE_NOT_APPROVABLE",
  INVOICE_BLACKLISTED: "INVOICE_BLACKLISTED",
  INVOICE_EMPTY: "INVOICE_EMPTY",
  MATCH_NOT_ALLOWED: "MATCH_NOT_ALLOWED",
  EXCEPTION_NOT_FOUND: "EXCEPTION_NOT_FOUND",
  EXCEPTION_NOT_EDITABLE: "EXCEPTION_NOT_EDITABLE",
  EXCEPTION_LINK_REQUIRED: "EXCEPTION_LINK_REQUIRED",
  EXCEPTION_DECISION_REQUIRED: "EXCEPTION_DECISION_REQUIRED",
  EXCEPTION_APPROVAL_REQUIRED: "EXCEPTION_APPROVAL_REQUIRED",
  EXCEPTION_INVALID_TYPE: "EXCEPTION_INVALID_TYPE",
  SCORECARD_NOT_FOUND: "SCORECARD_NOT_FOUND",
  GOVERNANCE_NOT_FOUND: "GOVERNANCE_NOT_FOUND",
  GOVERNANCE_NOT_PENDING: "GOVERNANCE_NOT_PENDING",
  GOVERNANCE_EVIDENCE_REQUIRED: "GOVERNANCE_EVIDENCE_REQUIRED",
  PREFERRED_THRESHOLD_NOT_MET: "PREFERRED_THRESHOLD_NOT_MET",
  EVALUATION_NOT_FOUND: "EVALUATION_NOT_FOUND",
  EVALUATION_ALREADY_SUBMITTED: "EVALUATION_ALREADY_SUBMITTED",
  EVALUATION_SUPPLIER_REQUIRED: "EVALUATION_SUPPLIER_REQUIRED",
  INVALID_EVALUATION_SCORE: "INVALID_EVALUATION_SCORE",
} as const;

export type ProcurementErrorCode =
  (typeof PROCUREMENT_ERROR_CODES)[keyof typeof PROCUREMENT_ERROR_CODES];

export const PROCUREMENT_USER_MESSAGES: Record<ProcurementErrorCode, string> = {
  INVALID_INPUT: "Please check the highlighted fields and try again.",
  SESSION_REQUIRED: "Your session has expired. Please sign in again.",
  BUSINESS_CONTEXT_REQUIRED: "Select a business before continuing.",
  CROSS_BUSINESS_ACCESS:
    "This supplier record belongs to another business and cannot be opened here.",
  UNAUTHORIZED: "You do not have permission to perform this action.",
  PARTY_NOT_FOUND: "The selected party could not be found for the current business.",
  PARTY_NOT_SUPPLIER:
    "This party does not have a supplier role. Confirm the supplier role before creating a procurement profile.",
  PROFILE_NOT_FOUND: "This supplier could not be found for the current business.",
  DUPLICATE_PROFILE:
    "This party already has a procurement profile. Open the existing supplier instead.",
  QUALIFICATION_NOT_FOUND:
    "This qualification record could not be found for the current business.",
  QUALIFICATION_EXPIRED: "This supplier's qualification has expired and must be reviewed.",
  SUPPLIER_SUSPENDED: "This supplier is suspended and cannot participate in procurement.",
  SUPPLIER_BLACKLISTED: "This supplier is blacklisted and cannot participate in procurement.",
  SUPPLIER_NOT_ELIGIBLE: "This supplier is not eligible to participate in procurement.",
  INVALID_CATEGORY: "Select a valid supplier category.",
  INVALID_CAPABILITY: "Select a valid supplier capability.",
  INVALID_STATUS: "Select a valid procurement status.",
  INVALID_STATUS_TRANSITION: "That status change is not allowed for this supplier.",
  STATUS_REASON_REQUIRED: "Enter a reason for this status change.",
  INVALID_QUALIFICATION_OUTCOME: "Select a valid qualification outcome.",
  INVALID_QUALIFICATION_TYPE: "Select a valid qualification type.",
  DOCUMENT_NOT_FOUND:
    "The selected document could not be found for this party in the current business.",
  NUMBERING_POLICY_MISSING: "Procurement numbering is not configured for this business.",
  CONCURRENT_UPDATE:
    "This supplier record was updated by someone else. Refresh and try again.",
  PROVIDER_ERROR: "The supplier details could not be saved. Please try again.",
  REQUEST_NOT_FOUND: "This purchase request could not be found for the current business.",
  EMPTY_REQUEST: "Add at least one line before submitting this request.",
  INVALID_QUANTITY: "Quantity must be greater than zero.",
  INVALID_ESTIMATED_VALUE: "Estimated value must be zero or more and include a currency.",
  CURRENCY_REQUIRED: "Select a currency.",
  BUDGET_SOURCE_REQUIRED: "Select where this request will be funded from.",
  BUDGET_REFERENCE_REQUIRED: "Enter a budget reference.",
  OVER_BUDGET: "This request is above the available budget and cannot proceed.",
  BUDGET_EVIDENCE_REQUIRED:
    "This request is above the available budget. Record budget approval evidence before submitting.",
  SELF_APPROVAL: "The person who submitted this request cannot approve it.",
  REQUEST_NOT_EDITABLE: "Approved requests cannot be changed. Return the request first.",
  INVALID_ORIGIN: "The inventory reorder reference could not be found.",
  DECISION_REASON_REQUIRED: "Enter a reason before continuing.",
  SOURCING_NOT_FOUND: "This sourcing event could not be found for the current business.",
  REQUEST_NOT_APPROVED: "Only approved purchase requests can be sourced.",
  CURRENCY_MISMATCH: "Budget and quotes must use the same currency.",
  INVITATION_NOT_FOUND: "This response link is not valid.",
  AWARD_INVALID: "The award could not be recorded. Check the selected suppliers and budget split.",
  TENDER_CLOSED: "This RFX is closed for submissions.",
  EXTENSION_INVALID: "The closing date could not be extended. Choose a later date.",
  INVITATION_REVOKED: "This response link is no longer valid.",
  EVALUATION_STAGE_INVALID: "Complete the prior evaluation step before continuing.",
  DUE_DILIGENCE_INCOMPLETE: "Complete due diligence checks before recording the award recommendation.",
  BIDS_NOT_OPENED: "Commercial responses are sealed until bids are opened for evaluation.",
  CRITERIA_NOT_LOCKED:
    "Evaluation criteria must be locked by the constituted committee before bids can be opened.",
  CRITERIA_LOCKED: "Evaluation criteria are locked and cannot be changed for this RFX.",
  AWARD_NOT_APPROVED: "The award decision must be approved before purchase orders can be created.",
  AWARD_OVERRIDE_REQUIRED: "Enter a reason when the award differs from the system recommendation.",
  AWARD_LINES_REQUIRED: "Award lines are required before a purchase order can be generated.",
  PO_NOT_FOUND: "This purchase order could not be found for the current business.",
  PO_ALREADY_EXISTS: "A purchase order already exists for this award.",
  SKIP_RFX_NOT_ALLOWED: "Organisation policy requires an RFX before creating a purchase order.",
  PO_NOT_EDITABLE: "This purchase order cannot be edited in its current state.",
  PO_VERSION_INVALID: "This purchase order version is no longer valid for the requested action.",
  PO_TOKEN_INVALID: "This purchase order link is not valid.",
  PO_TOKEN_REVOKED: "This purchase order link is no longer valid.",
  PO_REASON_REQUIRED: "A reason is required for this action.",
  CONTRACT_NOT_FOUND: "This contract could not be found for the current business.",
  CONTRACT_NOT_EDITABLE: "This contract cannot be edited in its current state.",
  CONTRACT_INVALID_STATE: "This action is not allowed for the contract's current state.",
  CONTRACT_CALLOFF_NOT_ALLOWED: "A purchase order cannot be created against this contract.",
  CONTRACT_CEILING_EXCEEDED: "This call-off would exceed the contract ceiling.",
  CONTRACT_ALREADY_EXISTS: "A contract already exists for this award.",
  DIRECT_CONTRACT_NOT_ALLOWED: "Contracts cannot be created directly from this purchase request.",
  CONTRACT_EXECUTION_EVIDENCE_REQUIRED:
    "An executed contract document is required before activation.",
  RECEIPT_NOT_FOUND: "This receipt could not be found for the current business.",
  RECEIPT_NOT_EDITABLE: "This receipt cannot be edited in its current state.",
  PO_NOT_RECEIVABLE: "This purchase order is not eligible for receiving.",
  OVER_RECEIPT_BLOCKED: "The received quantity exceeds the outstanding quantity.",
  INVALID_RECEIPT_QUANTITY: "Received quantity must be greater than zero.",
  PO_LINE_NOT_FOUND: "This purchase order line could not be found.",
  HANDOFF_FAILED: "The downstream handoff could not be completed.",
  INVOICE_NOT_FOUND: "This supplier invoice could not be found for the current business.",
  INVOICE_NOT_EDITABLE: "This supplier invoice cannot be edited in its current state.",
  INVOICE_DUPLICATE: "An invoice with this supplier number already exists.",
  INVOICE_PO_REQUIRED: "A purchase order reference is required for this invoice.",
  INVOICE_NOT_MATCHED: "This invoice must be matched before it can be approved.",
  INVOICE_NOT_APPROVABLE: "This invoice cannot be approved in its current state.",
  INVOICE_BLACKLISTED: "This supplier is blacklisted and the invoice cannot become payment-ready.",
  INVOICE_EMPTY: "Add at least one line before capturing this invoice.",
  MATCH_NOT_ALLOWED: "Matching is not allowed for this invoice in its current state.",
  EXCEPTION_NOT_FOUND: "This exception could not be found for the current business.",
  EXCEPTION_NOT_EDITABLE: "This exception cannot be changed in its current state.",
  EXCEPTION_LINK_REQUIRED: "Link at least one procurement record before saving this exception.",
  EXCEPTION_DECISION_REQUIRED: "A recorded decision is required before this exception can be closed.",
  EXCEPTION_APPROVAL_REQUIRED: "Approval is required before this exception can be closed.",
  EXCEPTION_INVALID_TYPE: "Select a valid exception type.",
  SCORECARD_NOT_FOUND: "This scorecard could not be found for the current business.",
  GOVERNANCE_NOT_FOUND: "This governance proposal could not be found.",
  GOVERNANCE_NOT_PENDING: "This governance proposal is no longer pending.",
  GOVERNANCE_EVIDENCE_REQUIRED: "Supporting evidence is required before this governance action can proceed.",
  PREFERRED_THRESHOLD_NOT_MET: "The supplier score is below the configured preferred threshold.",
  EVALUATION_NOT_FOUND: "This performance review could not be found.",
  EVALUATION_ALREADY_SUBMITTED: "This performance review has already been submitted and cannot be changed.",
  EVALUATION_SUPPLIER_REQUIRED: "Supplier self-review is required before the scorecard can be finalised.",
  INVALID_EVALUATION_SCORE: "Each measure score must be between 0 and 100.",
};

export class ProcurementError extends Error {
  readonly code: ProcurementErrorCode;
  readonly statusCode: number;
  readonly field?: string;

  constructor(
    code: ProcurementErrorCode,
    message: string = PROCUREMENT_USER_MESSAGES[code],
    statusCode = 400,
    options?: { field?: string }
  ) {
    super(message);
    this.name = "ProcurementError";
    this.code = code;
    this.statusCode = statusCode;
    this.field = options?.field;
  }
}
