/**
 * Purpose:
 * Configurable event categories, types, and source modules for Party Timeline.
 *
 * Design rationale:
 * BP-002 defines common codes; future Build Packs may introduce additional
 * values without schema changes — all stored as varchar codes.
 *
 * Implementation Package:
 * BP-002 / IP-010 – Party Timeline & Activity History
 */

/** Well-known event categories for BP-002. Additional categories allowed at runtime. */
export const PARTY_TIMELINE_EVENT_CATEGORIES = {
  REGISTRATION: "REGISTRATION",
  COMPLIANCE: "COMPLIANCE",
  COMMUNICATION: "COMMUNICATION",
  RELATIONSHIP: "RELATIONSHIP",
  ORGANIZATION: "ORGANIZATION",
  DOCUMENTS: "DOCUMENTS",
  GROUPS: "GROUPS",
  LIFECYCLE: "LIFECYCLE",
  OPERATIONS: "OPERATIONS",
  ENGAGEMENT: "ENGAGEMENT",
} as const;

export type PartyTimelineEventCategory =
  (typeof PARTY_TIMELINE_EVENT_CATEGORIES)[keyof typeof PARTY_TIMELINE_EVENT_CATEGORIES];

/** Well-known BP-002 event types. Future modules may use any string code. */
export const PARTY_TIMELINE_EVENT_TYPES = {
  PARTY_CREATED: "PARTY_CREATED",
  PARTY_UPDATED: "PARTY_UPDATED",
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  ROLE_REMOVED: "ROLE_REMOVED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_PRIMARY_SET: "ROLE_PRIMARY_SET",
  CONTACT_CREATED: "CONTACT_CREATED",
  CONTACT_UPDATED: "CONTACT_UPDATED",
  CONTACT_VERIFIED: "CONTACT_VERIFIED",
  CONTACT_REMOVED: "CONTACT_REMOVED",
  ADDRESS_CREATED: "ADDRESS_CREATED",
  ADDRESS_UPDATED: "ADDRESS_UPDATED",
  ADDRESS_REMOVED: "ADDRESS_REMOVED",
  RELATIONSHIP_CREATED: "RELATIONSHIP_CREATED",
  RELATIONSHIP_UPDATED: "RELATIONSHIP_UPDATED",
  RELATIONSHIP_REMOVED: "RELATIONSHIP_REMOVED",
  ORGANIZATION_UNIT_CREATED: "ORGANIZATION_UNIT_CREATED",
  ORGANIZATION_UNIT_UPDATED: "ORGANIZATION_UNIT_UPDATED",
  ORGANIZATION_UNIT_REMOVED: "ORGANIZATION_UNIT_REMOVED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_VERIFIED: "DOCUMENT_VERIFIED",
  DOCUMENT_EXPIRED: "DOCUMENT_EXPIRED",
  DOCUMENT_REMOVED: "DOCUMENT_REMOVED",
  IDENTIFIER_CAPTURED: "IDENTIFIER_CAPTURED",
  IDENTIFIER_UPDATED: "IDENTIFIER_UPDATED",
  IDENTIFIER_VERIFIED: "IDENTIFIER_VERIFIED",
  IDENTIFIER_EXPIRED: "IDENTIFIER_EXPIRED",
  IDENTIFIER_REMOVED: "IDENTIFIER_REMOVED",
  GROUP_JOINED: "GROUP_JOINED",
  GROUP_LEFT: "GROUP_LEFT",
  STATUS_CHANGED: "STATUS_CHANGED",
  ACTIVITY_CREATED: "ACTIVITY_CREATED",
  ACTIVITY_COMPLETED: "ACTIVITY_COMPLETED",
  ACTIVITY_OVERDUE: "ACTIVITY_OVERDUE",
  ACTIVITY_CANCELLED: "ACTIVITY_CANCELLED",
  ACTIVITY_DEFERRED: "ACTIVITY_DEFERRED",
  APPOINTMENT_SCHEDULED: "APPOINTMENT_SCHEDULED",
  APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_NO_SHOW: "APPOINTMENT_NO_SHOW",
  VISIT_PLANNED: "VISIT_PLANNED",
  VISIT_COMPLETED: "VISIT_COMPLETED",
  CALL_REPORT_SUBMITTED: "CALL_REPORT_SUBMITTED",
  CALL_REPORT_APPROVED: "CALL_REPORT_APPROVED",
  CALL_REPORT_RETURNED: "CALL_REPORT_RETURNED",
  CALL_REPORT_REJECTED: "CALL_REPORT_REJECTED",
  COMMUNICATION_SENT: "COMMUNICATION_SENT",
  COMMUNICATION_RECEIVED: "COMMUNICATION_RECEIVED",
  COMMUNICATION_BLOCKED: "COMMUNICATION_BLOCKED",
  CASE_OPENED: "CASE_OPENED",
  CASE_ESCALATED: "CASE_ESCALATED",
  CASE_RESOLVED: "CASE_RESOLVED",
  CASE_CLOSED: "CASE_CLOSED",
  GOVERNANCE_VALIDATED: "GOVERNANCE_VALIDATED",
  GOVERNANCE_OWNER_CHANGED: "GOVERNANCE_OWNER_CHANGED",
  GOVERNANCE_LOCKED: "GOVERNANCE_LOCKED",
  MERGE_PROPOSED: "MERGE_PROPOSED",
} as const;

export type PartyTimelineEventType =
  (typeof PARTY_TIMELINE_EVENT_TYPES)[keyof typeof PARTY_TIMELINE_EVENT_TYPES];

/** Identifies the originating module for timeline events. */
export const PARTY_TIMELINE_SOURCE_MODULES = {
  PARTY_MANAGEMENT: "PARTY_MANAGEMENT",
  CRM_ACTIVITY: "CRM_ACTIVITY",
  CRM_APPOINTMENT: "CRM_APPOINTMENT",
  CRM_VISIT: "CRM_VISIT",
  CRM_COMMUNICATION: "CRM_COMMUNICATION",
  CRM_CASE: "CRM_CASE",
  CRM_GOVERNANCE: "CRM_GOVERNANCE",
} as const;

export type PartyTimelineSourceModule =
  (typeof PARTY_TIMELINE_SOURCE_MODULES)[keyof typeof PARTY_TIMELINE_SOURCE_MODULES];

export const PARTY_TIMELINE_VISIBILITY = {
  STANDARD: "STANDARD",
  INTERNAL: "INTERNAL",
  RESTRICTED: "RESTRICTED",
} as const;

export type PartyTimelineVisibility =
  (typeof PARTY_TIMELINE_VISIBILITY)[keyof typeof PARTY_TIMELINE_VISIBILITY];

/** Default page size for timeline feed pagination. */
export const PARTY_TIMELINE_DEFAULT_PAGE_SIZE = 20;

/** Human-readable labels for event categories in UI filters. */
export const PARTY_TIMELINE_CATEGORY_LABELS: Record<
  PartyTimelineEventCategory,
  string
> = {
  REGISTRATION: "Registration",
  COMPLIANCE: "Compliance",
  COMMUNICATION: "Communication",
  RELATIONSHIP: "Relationship",
  ORGANIZATION: "Organization",
  DOCUMENTS: "Documents",
  GROUPS: "Groups",
  LIFECYCLE: "Lifecycle",
  OPERATIONS: "Operations",
  ENGAGEMENT: "Engagement",
};

/** Human-readable labels for source modules in UI filters. */
export const PARTY_TIMELINE_SOURCE_MODULE_LABELS: Record<
  PartyTimelineSourceModule,
  string
> = {
  PARTY_MANAGEMENT: "Party Management",
  CRM_ACTIVITY: "CRM Activities",
  CRM_APPOINTMENT: "CRM Appointments",
  CRM_VISIT: "CRM Visits",
  CRM_COMMUNICATION: "CRM Communications",
  CRM_CASE: "CRM Cases",
  CRM_GOVERNANCE: "CRM Governance",
};
