/**
 * Purpose:
 * ENG-003o — Canonical capability registry.
 *
 * Capabilities represent meaningful business actions/queries — not database functions.
 */

import {
  CAPABILITY_ACCESS_MODES,
  CHANNEL_CODES,
  type ChannelCode,
} from "@/core/channel-experience/constants";
import type { ChannelCapabilityDefinition } from "@/core/channel-experience/types";
import { PROCUREMENT_PERMISSIONS } from "@/modules/procurement/constants";

const STAFF_WEB_CHANNELS: readonly ChannelCode[] = [
  CHANNEL_CODES.WEB,
  CHANNEL_CODES.STAFF,
  CHANNEL_CODES.APP,
];

const WEB_CUSTOMER_CHANNELS: readonly ChannelCode[] = [
  CHANNEL_CODES.WEB,
  CHANNEL_CODES.APP,
];

function capability(
  definition: ChannelCapabilityDefinition
): ChannelCapabilityDefinition {
  return definition;
}

export const CAPABILITY_REGISTRY: Record<string, ChannelCapabilityDefinition> = {
  OFFERING_VIEW: capability({
    id: "OFFERING_VIEW",
    owningDomain: "BP-003",
    requiredPermission: "ProductManagement.Offering.Read",
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  PRICE_QUERY: capability({
    id: "PRICE_QUERY",
    owningDomain: "BP-005",
    requiredPermission: "CommercialManagement.Config.Read",
    allowedChannels: [...WEB_CUSTOMER_CHANNELS, CHANNEL_CODES.CONVERSATIONAL],
    requiresAuthentication: false,
    requiresStaffContext: false,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  STOCK_AVAILABILITY_QUERY: capability({
    id: "STOCK_AVAILABILITY_QUERY",
    owningDomain: "BP-008",
    requiredPermission: "InventoryManagement.Stock.Read",
    allowedChannels: [...WEB_CUSTOMER_CHANNELS, CHANNEL_CODES.CONVERSATIONAL],
    requiresAuthentication: true,
    requiresStaffContext: false,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  CREATE_QUOTATION: capability({
    id: "CREATE_QUOTATION",
    owningDomain: "BP-004",
    requiredPermission: "CustomerRelationshipManagement.Quotation.Create",
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.WRITE,
    auditRequired: true,
  }),
  CREATE_SALE: capability({
    id: "CREATE_SALE",
    owningDomain: "BP-006",
    requiredPermission: "SalesManagement.Order.Create",
    allowedChannels: [...WEB_CUSTOMER_CHANNELS, CHANNEL_CODES.API],
    requiresAuthentication: true,
    requiresStaffContext: false,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.WRITE,
    auditRequired: true,
  }),
  VIEW_ORDER: capability({
    id: "VIEW_ORDER",
    owningDomain: "BP-006",
    requiredPermission: "SalesManagement.Order.Read",
    allowedChannels: [...WEB_CUSTOMER_CHANNELS, CHANNEL_CODES.API],
    requiresAuthentication: true,
    requiresStaffContext: false,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  INITIATE_PAYMENT: capability({
    id: "INITIATE_PAYMENT",
    owningDomain: "BP-007",
    requiredPermission: "PaymentManagement.Transaction.Create",
    allowedChannels: [...WEB_CUSTOMER_CHANNELS, CHANNEL_CODES.API],
    requiresAuthentication: true,
    requiresStaffContext: false,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.WRITE,
    auditRequired: true,
  }),
  VIEW_PAYMENT_STATUS: capability({
    id: "VIEW_PAYMENT_STATUS",
    owningDomain: "BP-007",
    requiredPermission: "PaymentManagement.Transaction.Read",
    allowedChannels: [...WEB_CUSTOMER_CHANNELS, CHANNEL_CODES.API],
    requiresAuthentication: true,
    requiresStaffContext: false,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  VIEW_SUPPLIER: capability({
    id: "VIEW_SUPPLIER",
    owningDomain: "BP-009",
    requiredPermission: PROCUREMENT_PERMISSIONS.VIEW,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  CREATE_PROCUREMENT_REQUEST: capability({
    id: "CREATE_PROCUREMENT_REQUEST",
    owningDomain: "BP-009",
    requiredPermission: PROCUREMENT_PERMISSIONS.REQUEST_CREATE,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.WRITE,
    auditRequired: true,
  }),
  VIEW_PROCUREMENT_STATUS: capability({
    id: "VIEW_PROCUREMENT_STATUS",
    owningDomain: "BP-009",
    requiredPermission: PROCUREMENT_PERMISSIONS.REQUEST_READ,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  PROCUREMENT_DASHBOARD: capability({
    id: "PROCUREMENT_DASHBOARD",
    owningDomain: "BP-009",
    requiredPermission: PROCUREMENT_PERMISSIONS.VIEW,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  PROCUREMENT_WORKSPACE: capability({
    id: "PROCUREMENT_WORKSPACE",
    owningDomain: "BP-009",
    requiredPermission: null,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  PARTY_WORKSPACE: capability({
    id: "PARTY_WORKSPACE",
    owningDomain: "BP-002",
    requiredPermission: null,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  PRODUCT_WORKSPACE: capability({
    id: "PRODUCT_WORKSPACE",
    owningDomain: "BP-003",
    requiredPermission: null,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  CRM_WORKSPACE: capability({
    id: "CRM_WORKSPACE",
    owningDomain: "BP-004",
    requiredPermission: null,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  COMMERCIAL_WORKSPACE: capability({
    id: "COMMERCIAL_WORKSPACE",
    owningDomain: "BP-005",
    requiredPermission: "CommercialManagement.Config.Read",
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  COMMERCIAL_GOVERNANCE_WORKSPACE: capability({
    id: "COMMERCIAL_GOVERNANCE_WORKSPACE",
    owningDomain: "BP-005",
    requiredPermission: null,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  TAX_COMPLIANCE_WORKSPACE: capability({
    id: "TAX_COMPLIANCE_WORKSPACE",
    owningDomain: "BP-005",
    requiredPermission: null,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  SALES_WORKSPACE: capability({
    id: "SALES_WORKSPACE",
    owningDomain: "BP-006",
    requiredPermission: null,
    allowedChannels: [...WEB_CUSTOMER_CHANNELS, CHANNEL_CODES.API],
    requiresAuthentication: true,
    requiresStaffContext: false,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  PAYMENT_WORKSPACE: capability({
    id: "PAYMENT_WORKSPACE",
    owningDomain: "BP-007",
    requiredPermission: null,
    allowedChannels: [...WEB_CUSTOMER_CHANNELS, CHANNEL_CODES.API],
    requiresAuthentication: true,
    requiresStaffContext: false,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
  INVENTORY_WORKSPACE: capability({
    id: "INVENTORY_WORKSPACE",
    owningDomain: "BP-008",
    requiredPermission: null,
    allowedChannels: STAFF_WEB_CHANNELS,
    requiresAuthentication: true,
    requiresStaffContext: true,
    requiresCustomerContext: false,
    requiresApproval: false,
    accessMode: CAPABILITY_ACCESS_MODES.READ,
    auditRequired: false,
  }),
};

export function getCapabilityDefinition(
  capabilityId: string
): ChannelCapabilityDefinition | null {
  return CAPABILITY_REGISTRY[capabilityId] ?? null;
}

export function listRegisteredCapabilities(): readonly ChannelCapabilityDefinition[] {
  return Object.values(CAPABILITY_REGISTRY);
}
