/**
 * Purpose:
 * ENG-003o — Domain workspace capability IDs and permission prefix mapping.
 */

export const DOMAIN_WORKSPACE_CAPABILITIES = {
  PARTY: "PARTY_WORKSPACE",
  PRODUCT: "PRODUCT_WORKSPACE",
  CRM: "CRM_WORKSPACE",
  COMMERCIAL: "COMMERCIAL_WORKSPACE",
  COMMERCIAL_GOVERNANCE: "COMMERCIAL_GOVERNANCE_WORKSPACE",
  TAX_COMPLIANCE: "TAX_COMPLIANCE_WORKSPACE",
  SALES: "SALES_WORKSPACE",
  PAYMENT: "PAYMENT_WORKSPACE",
  INVENTORY: "INVENTORY_WORKSPACE",
  PROCUREMENT: "PROCUREMENT_WORKSPACE",
} as const;

export type DomainWorkspaceCapability =
  (typeof DOMAIN_WORKSPACE_CAPABILITIES)[keyof typeof DOMAIN_WORKSPACE_CAPABILITIES];

/** Permission module prefix used to validate workspace access when seeded. */
export const DOMAIN_PERMISSION_PREFIXES: Record<
  DomainWorkspaceCapability,
  string | null
> = {
  [DOMAIN_WORKSPACE_CAPABILITIES.PARTY]: "PartyManagement.",
  [DOMAIN_WORKSPACE_CAPABILITIES.PRODUCT]: null,
  [DOMAIN_WORKSPACE_CAPABILITIES.CRM]: null,
  [DOMAIN_WORKSPACE_CAPABILITIES.COMMERCIAL]: "CommercialManagement.",
  [DOMAIN_WORKSPACE_CAPABILITIES.COMMERCIAL_GOVERNANCE]: "CommercialManagement.",
  [DOMAIN_WORKSPACE_CAPABILITIES.TAX_COMPLIANCE]: "CommercialManagement.",
  [DOMAIN_WORKSPACE_CAPABILITIES.SALES]: null,
  [DOMAIN_WORKSPACE_CAPABILITIES.PAYMENT]: null,
  [DOMAIN_WORKSPACE_CAPABILITIES.INVENTORY]: null,
  [DOMAIN_WORKSPACE_CAPABILITIES.PROCUREMENT]: "Procurement.",
};
